"""Few-shot exemplars for the base-model (`freeform`) prompt.

Three (draft, notes, rewrite) triples. Each draft is a generic instruct-model
paragraph; the notes are the particulars an author vouched for; the rewrite
keeps every claim in order, at least half the draft's content words, and adds
no particular that is not in the notes. They exist to show a base checkpoint
the *shape* of the task (research/24 §6.3-6.4): a base model continues a
pattern, and this is the pattern. Written for this project on 2026-09-07 and
checked against the shipping gates by `.flip/anchor/r4/check_r4.py`.
"""

from __future__ import annotations

from typing import Tuple

__all__ = ["FREEFORM_SHOTS"]

#: (topic, draft, notes, rewrite)
FREEFORM_SHOTS: Tuple[Tuple[str, str, str, str], ...] = (
    (
        "the role of gut microbiota in metabolic disease",
        "Gut microbiota plays a crucial role in the development and progression of metabolic diseases such as diabetes, obesity, and non-alcoholic fatty liver disease. These microorganisms, which reside in the gastrointestinal tract, help break down dietary components, synthesize essential nutrients, and regulate the immune system. Dysbiosis, or an imbalance in the gut microbiota, can lead to chronic inflammation, altered metabolism, and increased insulin resistance, contributing to metabolic disease pathogenesis. Key considerations include the impact of diet, lifestyle, and environmental factors on gut microbial composition and function. Research suggests that manipulating the gut microbiota through probiotics, prebiotics, and fecal microbiota transplantation could be a promising therapeutic approach. To address metabolic diseases, promoting a balanced diet rich in fiber, reducing processed foods, and fostering a healthy gut microbiome are essential. Further, personalized medicine strategies that consider individual gut microbiota profiles could pave the way for more effective prevention and treatment of metabolic diseases.",
        "- The gut microbiota is implicated in obesity, type 2 diabetes and non-alcoholic fatty liver disease, though most of the evidence is from mice.\n- Turnbaugh's 2006 transplant experiments made obese mice from lean ones and started the field.\n- Diet moves the microbiome within days, as David and colleagues showed in 2014, and lifestyle and antibiotics move it too.",
        "Gut microbiota is implicated in the development and progression of metabolic diseases such as type 2 diabetes, obesity, and non-alcoholic fatty liver disease, though most of the evidence is from mice. These microorganisms reside in the gastrointestinal tract, where they help break down dietary components, synthesize essential nutrients, and regulate the immune system. Turnbaugh's 2006 transplant experiments, which made obese mice from lean ones, started the field. Dysbiosis, an imbalance in the gut microbiota, can lead to chronic inflammation, altered metabolism, and increased insulin resistance, and that is the proposed route to metabolic disease pathogenesis. Diet moves microbial composition and function within days, as David and colleagues showed in 2014, and lifestyle, antibiotics and other environmental factors move it too. Research suggests manipulating the gut microbiota through probiotics, prebiotics and fecal microbiota transplantation as a therapeutic approach. A balanced diet rich in fiber and fewer processed foods remain the reliable advice for a healthy gut microbiome. Personalized medicine strategies that consider individual gut microbiota profiles could make prevention and treatment of metabolic diseases more effective, on the same mouse-heavy evidence.",
    ),
    (
        "air pollution and cognitive development in children",
        "Air pollution, a pervasive environmental issue, significantly impacts cognitive development in children, making it a critical public health concern. Exposure to pollutants like particulate matter (PM2.5) and nitrogen dioxide can lead to developmental delays, reduced IQ scores, and impairments in memory and learning abilities. These effects are particularly pronounced during fetal development and early childhood, as the brain is most vulnerable to damage during these periods. The primary considerations in addressing this issue include reducing emissions from sources such as vehicles and industrial activities, enhancing air quality monitoring, and promoting public awareness. Policy measures, such as stricter emission standards and incentives for cleaner technologies, are essential. Additionally, urban planning that integrates green spaces and promotes public transportation can help mitigate exposure. Public health strategies that include early detection and intervention are also crucial to minimize the long-term cognitive impacts on children.",
        "- Fine particulate matter, PM2.5, and nitrogen dioxide cross the placenta and the blood-brain barrier.\n- The Columbia cohort in New York found prenatal exposure to combustion pollutants cut IQ by about 4 to 5 points at age five, roughly the effect of low-level lead.\n- Memory and learning show smaller deficits in the Barcelona BREATHE study of 2,700 schoolchildren, where traffic pollution slowed working-memory growth by about 13 percent over a year.\n- Emission controls on vehicles and industry are the lever that works: London's Ultra Low Emission Zone cut roadside NO2 by about 46 percent in central London by 2022.\n- Air quality monitoring is thin in the poor countries where exposure is highest; Delhi runs at ten times the WHO guideline for months.",
        "Air pollution impairs cognitive development in children, a public health concern. Fine particulate matter (PM2.5) and nitrogen dioxide cross the placenta and blood-brain barrier; exposure is linked to developmental delays, reduced IQ scores, and impaired memory and learning. The Columbia cohort in New York found prenatal exposure to combustion pollutants cut IQ by about 4 to 5 points at age five; the effects are most pronounced in fetal development and early childhood, when the brain is most vulnerable. The Barcelona BREATHE study of 2,700 schoolchildren found traffic pollution slowed working-memory growth by about 13 percent over a year, a smaller deficit, and such cohorts cannot fully separate pollution from poverty. Reducing emissions from vehicles and industrial activities is the lever that works, while air quality monitoring and public awareness remain thin where exposure is highest. Stricter emission standards, incentives for cleaner technologies, urban planning with green spaces and public transportation, and early detection and intervention follow from that. London's Ultra Low Emission Zone cut roadside NO2 by about 46 percent by 2022.",
    ),
    (
        "the role of libraries in the digital age",
        "In the digital age, libraries play a crucial role as essential community hubs that bridge the gap between traditional and digital resources. They serve as gateways to knowledge, offering access to a wide array of digital materials, including e-books, online databases, and digital archives. Libraries also provide crucial services such as internet access, digital literacy training, and support for remote learning, which are vital for underserved communities. Key considerations include ensuring equitable access to digital resources, enhancing digital literacy, and integrating technology to improve user experience. To address these, libraries must invest in robust digital infrastructure, collaborate with local partners to expand access, and offer tailored training programs. By doing so, libraries can continue to fulfill their mission of empowering individuals and communities to thrive in the digital age.",
        "- The US has about 9,000 public library systems and visits ran about 1.2 billion in 2019.\n- E-books, online databases and digital archives are now standard, and publishers charge libraries about three times the consumer price for an e-book licence that expires after two years or 26 loans.\n- Internet access is the service that grew: about a quarter of American library users come for the computers or the Wi-Fi, and in rural areas the library is often the only free connection.\n- Digital literacy training and support for remote learning happened in 2020 through the car park Wi-Fi.\n- Infrastructure investment runs about 12 dollars per capita in the US and 20 pounds in the UK, where 800 branches closed between 2010 and 2020.",
        "Libraries in the digital age are community hubs that bridge traditional and digital resources; the US has about 9,000 public library systems and visits ran about 1.2 billion in 2019. They remain gateways to knowledge, offering e-books, online databases and digital archives, though publishers charge libraries about three times the consumer price for an e-book licence. Internet access, digital literacy training and support for remote learning are the services that grew, and they matter most for underserved communities; about a quarter of American library users come for the computers or the Wi-Fi. Equitable access to digital resources, digital literacy and technology that improves the user experience are the considerations, and the third is the least evidenced. That means investing in digital infrastructure, collaborating with local partners to expand access and offering tailored training programs. Infrastructure investment runs about 12 dollars per capita in the US and 20 pounds in the UK, where 800 branches closed between 2010 and 2020.",
    ),
)
