"""Detector-guided decoding: generate under a detector's own signal.

Why this module exists, and what it is *not*
--------------------------------------------
`pipeline.py` measured three things into the ground and wrote them down:
rule-based rewriting flips 0 verdicts of 9, paragraph-level best-of-N over an
instruction-tuned 3B flips 0 of 9, and the controlling measurement is that
pushing *genuine human text* through the same model raises its detector score
from 0.18 to 0.66. The output distribution of the model is the thing the
detector fires on. Asking the model nicely does not move that distribution, so
best-of-N has nothing good to select from.

Detector-guided decoding (research/03 B.8, research/05 §1.2 -- Cheng,
Sadasivan et al., *Adversarial Paraphrasing*, NeurIPS 2025) attacks that
directly. Instead of describing the target register in a prompt, you put the
detector *inside* the decoding loop and steer away from it using its own
gradient-free signal. The published method scores the top-k next **tokens** at
every step with a guide detector and emits the lowest-scoring one -- "a
targeted, detector-guided beam search at depth one" -- and reports an 87.88%
mean reduction in TPR@1%FPR across eight detectors.

Two variants are implemented here.

**A. Segment-guided search (`GuideMode.SEGMENT`, the default).** Generation
runs sentence by sentence. At each step every live hypothesis proposes
`n_samples` continuations of the *next source sentence*; each is scored with
the guide in context; the best `beam_width` survive. This is best-of-N at
sentence granularity with a beam, which is a far finer control surface than
the paragraph-level best-of-N that already failed: a 9-sentence paragraph with
beam 3 and 4 samples gives 3^9 reachable sequences explored through 108 guide
calls, against 6 whole-paragraph draws.

**B. Token-level guidance (`GuideMode.TOKEN`).** The published method, with one
concession to latency: the guide runs every `guidance_interval` tokens rather
than every token, because a guide call is ~28 ms and a 60-token sentence at
m=1 with k=8 is 13 seconds *for one sentence*. At the guided steps the LM's
top-k logprobs are reweighted by the guide's delta (`reweight_logprobs`) and a
token is sampled from the reweighted distribution. Off by default; see
`GuidedConfig.mode` and the measured numbers in the module test suite.

The guide is not the yardstick, and the distinction is load-bearing
-------------------------------------------------------------------
The in-loop guide is `MayZhou/e5-small-lora-ai-generated-detector` -- 33M
parameters, measured here at 28.5 ms a document against desklib's 161 ms.
research/05 §4 names exactly this checkpoint for exactly this job. It is also,
by this repo's own bench (`detectors.local.PUBLISHED_DETECTORS["fast"]`), a
detector that calls 8 of 14 genuine human PMC paragraphs AI. It is a search
heuristic. It is not evidence.

So **every reported probability in this module's output comes from the
yardstick**, `desklib/ai-text-detector-v1.01`, the same detector `pipeline.py`
reports and the same one `/api/detect` defaults to. The guide's own score is
carried alongside, in a separate `guide` block, labelled, and never substituted
for the yardstick. `summary["verdict_flipped"]`, `after["ai_probability"]` and
`summary["risk_delta"]` are desklib numbers and nothing else. research/08 §2.2
is blunt about why: a surrogate's posterior "carries no information about a
different classifier trained on different data", and best-of-N takes the
*argmax* of the surrogate, which is precisely where surrogate and target
disagree most. `summary["guide_transfer"]` reports that gap explicitly rather
than hoping about it.

What this actually achieves, measured
-------------------------------------
Measured on an M4 Pro against `desklib/ai-text-detector-v1.01`, on the same
corpus `.llmbench/bench.py` used for the LLM pipeline -- 9 AI paragraphs (3
hand-written in the stereotypical register, 6 generated by
Qwen2.5-3B-Instruct) and 5 human PMC paragraphs -- at beam 3 x 4 samples.

===========================  ==========  ==========  ============  =========
metric                       rule-based  LLM best-6  **guided**    unguided
                                                                   beam
===========================  ==========  ==========  ============  =========
verdict flips (ai -> human)  **0 of 9**  **0 of 9**  **0 of 9**    0 of 9
mean p(AI) change            -0.000013   -0.000130   -0.014619     -0.000649
mean logit(p) change         -0.36       -1.67       **-2.92**     -1.82
best single logit change     --          -2.90       **-8.57**     -4.79
mean sentence-length CV      0.219       0.304       **0.368**     0.202
in the 0.42-0.60 CV band     0 of 9      0 of 9      **4 of 9**    0 of 9
mean AI vocabulary per 1k    14.9        13.7        11.8          --
mean content overlap         --          --          0.79          0.85
mean wall clock              < 0.1 s     12.4 s      43 s          --
===========================  ==========  ==========  ============  =========

**It does not flip the verdict either.** That is the third independent
negative result on this corpus and it is the headline; the probability drop is
0.015 and the honest reading of it is "nothing". Say that first.

Three things it *does* do, and they are real:

1. It moves the detector further than anything else tried here. In
   probability the numbers are meaningless because desklib is saturated -- it
   returns 0.99998 for every source paragraph -- so the movement is quoted in
   logits, where a flip needs **-11.03** and this gets **-2.92** on average
   and **-8.57** on its best sample (`ai-gen-sleep`, 1.0000 -> 0.8776). The
   LLM pipeline's much-quoted "0.0001" was -1.67 logits. Guided decoding is
   1.75x that and is the first method here to land a sample within 2.5 logits
   of the threshold.
2. It is the first method here to reach the human sentence-length CV band:
   0.232 -> 0.368 mean, 4 of 9 samples inside 0.42-0.60, against 0 of 9 for
   both earlier engines. That comes from the guide, not from the beam -- see
   the ablation below.
3. It does not damage human text. Over the 5 PMC paragraphs the largest
   upward movement was **0.0000** and the mean change was -0.0278 (one
   paragraph improved from 0.1765 to 0.0375); 4 of 5 were returned untouched
   because the paragraph gate rejected every finalist.

Two ablations, and what they say about why it fails
----------------------------------------------------
**The guide is doing work.** Running the identical beam search, identical
gates and identical sampling with no guide at all (`guide=False`) gives -1.82
logits and moves the sentence-length CV the *wrong* way, 0.232 -> 0.202, with
0 of 9 in the band. So roughly a third of the movement and all of the
stylometric gain is attributable to the detector signal rather than to
resampling.

**But the weak proxy is not the reason it fails.** The obvious suspect is the
33M guide: research/08 §3.2 measures detector-to-detector transfer as "real
but wildly uneven", and this run reproduces exactly that shape -- the guide's
own score falls 0.94 -> 0.82 while desklib falls 0.99998 -> 0.985, a 6.7x
disagreement in probability, with a Pearson correlation of 0.87 between the
two deltas. Directionally honest, wildly attenuated in magnitude.

So the experiment was run again with **desklib itself as the in-loop guide** --
no proxy, no transfer gap, the search optimising the exact classifier that
judges it, at 161 ms a call instead of 28 ms. Result: **0 of 9 flips**,
-3.98 logits, mean p(AI) change -0.0042. Better in logits than the e5 guide,
worse in probability, and no closer to a verdict.

That is the finding. **The binding constraint is the generator, not the
verifier.** Search cannot select text that the model never proposes, and
across 9 paragraphs x 7 sentences x 12 candidates -- roughly 750 sentence
rewrites scored against desklib directly -- the best assembled paragraph the
model produced still scored 0.977. It is the same wall `pipeline.py` hit from
the other side: passing genuine human text through this checkpoint *raises*
its score from 0.18 to 0.66, so the model's output distribution is inside the
detector's AI region no matter which path through it you pick. Guided decoding
searches that region more finely than best-of-N does, and gets meaningfully
further, and the region does not reach 0.5.

Variant B, measured
-------------------
Token-level guidance was run at a *matched* budget against variant A -- beam 1
x 2 samples, m=8, k=8, over the three hand-written AI paragraphs -- because
comparing it against variant A's default beam 3 x 4 would compare search
budgets, not methods. At 12.4 s a paragraph against variant A's 12.3 s:

=========================  ==========  ==========
metric                     A segment   B token
=========================  ==========  ==========
verdict flips              0 of 3      0 of 3
mean logit(p) change       -2.07       **-3.00**
best single logit change   -3.71       **-6.07**
guide calls per paragraph  9           329
guide seconds              0.2         2.3
decode rate                26.9 tok/s  21.8 tok/s
=========================  ==========  ==========

So the finer control surface is worth about 45% more movement per second, and
`m=8` is why: 329 guide calls cost 2.3 s at 28 ms each, which is affordable,
while `m=1` on the same paragraphs would be roughly 2,600 calls and 74 s. It
still flips nothing, on three samples, and three samples is not a result --
it is reported because a measured number beats an unmeasured claim, not
because it settles anything. `GuideMode.SEGMENT` stays the default because it
batches and variant B cannot.

The Gao/Stroebl reading in research/08 §2.1 applies but is not the whole
story: this is not an over-optimisation turnover, since gold performance kept
improving with the better guide. It is the Stroebl ceiling -- an imperfect
*generator* bounds what any amount of verification can reach.

Gates are `pipeline.py`'s, imported not reimplemented
-----------------------------------------------------
`pipeline._invariant_failures` (numbers, quotations, citations and dates as
exact multisets; the entity test directional) and `pipeline._gate_candidate`
(length ratio, floor, content overlap, invariants, unchanged) run on the
assembled paragraph exactly as they run on an LLM candidate, and
`pipeline._scrub` runs the same deterministic transform passes. A second copy
of a meaning gate is how two code paths start disagreeing about what a safe
edit is. There is one addition, not a relaxation: `sentence_gate` applies the
same invariant check *per sentence* during the search, so a candidate that
drops a number is rejected at the step that produced it instead of poisoning
a whole beam. A sentence whose candidates all fail falls back to the source
sentence verbatim, which is reported, never hidden.

Progress events
---------------
`stream()` yields `pipeline.ProgressEvent` -- the same class, not a lookalike
-- over the same stage names in the same order::

    analyze plan generate scrub score verify select finalize

`STAGES` is re-exported so `/api/humanize/guided/health` can publish it and the
frontend's checklist works unchanged. Inside `generate` the `detail` string
reports the beam step ("paragraph 1 of 2, sentence 4 of 9, beam 3 x 4
samples"); no new stage was needed for the search because the search *is* the
generate stage. `score` is where the yardstick runs, and its detail says so.
"""

from __future__ import annotations

import math
import re
import time
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, Iterator, List, Optional, Sequence, Tuple

from ..detectors import yardstick as yardstick_mod
from ..features import extract_from_document
from ..text import Document, normalize, split_paragraphs, split_sentences, words
from . import llm as llm_mod
from . import pipeline as pipeline_mod
from .pipeline import AI_THRESHOLD, ProgressEvent, content_overlap

__all__ = [
    "STAGES",
    "GUIDE_MODEL",
    "GUIDE_ENGINE",
    "YARDSTICK_MODEL",
    "GuideMode",
    "SENTENCE_MOVES",
    "GuidedConfig",
    "SentenceCandidate",
    "Hypothesis",
    "GuidedParagraph",
    "GuidedResult",
    "build_sentence_prompt",
    "clean_sentence",
    "guide_context",
    "select_beam",
    "sentence_gate",
    "reweight_logprobs",
    "sentence_max_tokens",
    "stream",
    "humanize_guided",
    "guided_available",
    "guided_unavailable_reason",
]


#: The UI's checkbox list. Identical to `pipeline.STAGES` on purpose: the
#: frontend builds its checklist from whatever `/health` publishes, and this
#: pipeline genuinely has the same eight phases.
STAGES: Tuple[str, ...] = pipeline_mod.STAGES

#: The in-loop guide. 33M parameters, ~28 ms a document as measured on an M4
#: Pro against desklib's ~161 ms. research/05 §4 names this checkpoint for the
#: inner optimisation loop. READ `PUBLISHED_DETECTORS["fast"]`: it calls 8 of
#: 14 genuine human PMC paragraphs AI. Search heuristic, never a verdict.
GUIDE_MODEL = "MayZhou/e5-small-lora-ai-generated-detector"

#: Its `/api/detect` engine name, so a caller can reproduce the guide's number.
GUIDE_ENGINE = "fast"

#: The yardstick. Every probability this module reports comes from here.
#: Spelled out rather than imported so `humanizer.humanize` still imports on a
#: machine with no torch; `_yardstick()` does the real import lazily.
YARDSTICK_MODEL = "desklib/ai-text-detector-v1.01"

#: The guide's head shape. `resolve_head` cannot infer it from a merged-LoRA
#: e5 checkpoint's `architectures`, and guessing wrong inverts every score, so
#: it is stated (`PUBLISHED_DETECTORS["fast"]["head"]` says the same thing).
GUIDE_HEAD = "softmax"


class GuideMode:
    """Which variant of detector-guided decoding to run.

    `SEGMENT` is variant A: a sentence-granularity beam search, tractable
    inside the 30-second budget. `TOKEN` is variant B, the published
    per-token method with the guide throttled to every m tokens.
    """

    SEGMENT = "segment"
    TOKEN = "token"

    ALL = (SEGMENT, TOKEN)


class GuideContext:
    """What the guide is shown when it scores a partial rewrite.

    `FULL` -- the rewritten prefix, the candidate, then the *source's* remaining
    sentences. The guide sees a constant-length, complete-looking document at
    every step, so the score difference between two candidates is attributable
    to the candidates rather than to how much text exists yet. Every detector
    here is document-trained and `detectors.local.MIN_RELIABLE_CHARS` is 250;
    scoring a 20-word prefix asks it a question it was never trained on.

    `PREFIX` -- the rewritten prefix plus the candidate, and nothing else. The
    literal reading of "score prefix + candidate". Kept because it is the
    honest baseline for whether `FULL` is doing anything.

    `SENTENCE` -- the candidate alone. Fastest, and the least reliable.
    """

    FULL = "full"
    PREFIX = "prefix"
    SENTENCE = "sentence"

    ALL = (FULL, PREFIX, SENTENCE)


#: Sentence-level structural moves. The paragraph-level `llm.CANDIDATE_SPECS`
#: do not transfer: "open on the concrete detail, not the abstraction" is an
#: instruction about a paragraph's shape and means nothing applied to one
#: sentence. These are the moves that change a *sentence's* shape, which is
#: what sentence-length CV and burstiness are made of (research/04, /10).
#: The temperature offset rises down the list so that the diversity comes from
#: the instruction first and the sampler second -- `pipeline.py` measured
#: temperature alone buying almost nothing.
SENTENCE_MOVES: Tuple[Tuple[str, float], ...] = (
    ("Keep it about the same length, but change the word order.", 0.7),
    ("Make it short and blunt. Under ten words if you can.", 0.9),
    ("Let it run long and a little uneven, with a clause that doubles back.", 1.0),
    ("Start with the concrete thing, not the abstraction.", 0.85),
    ("Split it into two sentences of very different lengths.", 1.05),
    ("Fold in a plain, ordinary word where a formal one sits now.", 0.95),
    ("Turn it around: put the end of the sentence at the front.", 1.1),
    ("Say it the way you would say it out loud to one person.", 1.15),
)


def sentence_moves(n: int) -> List[Tuple[str, float]]:
    """`n` (move, temperature) pairs, cycling with a rising temperature.

    Past `len(SENTENCE_MOVES)` the list repeats with +0.1 on the temperature
    per lap, capped at 1.4. Beyond about 1.4 Qwen2.5-3B-Instruct-4bit starts
    emitting non-words, which is a gate failure rather than diversity.
    """
    if n <= 0:
        raise ValueError("n must be positive")
    out: List[Tuple[str, float]] = []
    for i in range(n):
        move, temp = SENTENCE_MOVES[i % len(SENTENCE_MOVES)]
        lap = i // len(SENTENCE_MOVES)
        out.append((move, round(min(1.4, temp + 0.1 * lap), 3)))
    return out


# ------------------------------------------------------------------ prompts


#: The system turn for a single-sentence rewrite. Deliberately shorter than
#: `llm._SYSTEM_FAITHFUL`: at sentence granularity the prompt is re-encoded
#: once per sentence per beam per sample, so a 300-token system message is
#: paid `beam x samples x sentences` times. The style exemplar is dropped for
#: the same reason and because the guide, not the prompt, is what steers here.
#: That is the whole thesis of the module -- if the prompt could do it,
#: `pipeline.py` would already have done it.
_SYSTEM = (
    "You rewrite one sentence at a time. You are a person writing, not an "
    "assistant: no preamble, no commentary, no quotation marks around the "
    "answer. Keep every number, name, date and quotation exactly as given. "
    "Output the rewritten sentence and nothing else."
)


def build_sentence_prompt(
    prefix: str,
    source_sentence: str,
    move: str = "",
    following: str = "",
) -> llm_mod.Prompt:
    """The prompt for one candidate rewrite of one sentence.

    Args:
        prefix: the rewrite so far. Shown as context so the continuation
            actually continues -- without it the model re-establishes the
            subject every sentence and the paragraph reads as a list.
        source_sentence: the sentence being rewritten. Placed last: this is
            the one thing the model must act on, and instruction-following
            degrades with distance from the end of the context.
        move: one of `SENTENCE_MOVES`, or empty.
        following: the next source sentence, shown as "what comes next" so the
            model does not write a closing sentence in the middle of a
            paragraph. Optional; empty on the last sentence, which is the one
            place a closing cadence is correct.

    Returns:
        A chat `llm.Prompt`, ready for any `llm.Backend`.

    Raises:
        ValueError: when `source_sentence` is empty.
    """
    if not source_sentence or not source_sentence.strip():
        raise ValueError("source_sentence must not be empty")

    parts: List[str] = []
    if prefix and prefix.strip():
        parts.append("Your rewrite so far:\n" + prefix.strip())
    else:
        parts.append("You are starting the paragraph.")
    if following and following.strip():
        parts.append(
            "After this sentence the draft goes on to say:\n" + following.strip()
        )
    if move:
        parts.append("How to write it: " + move)
    parts.append("Rewrite this sentence:\n" + source_sentence.strip())
    return llm_mod.Prompt(
        kind="chat",
        messages=(("system", _SYSTEM), ("user", "\n\n".join(parts))),
    )


_QUOTE_WRAP_RE = re.compile(r'^\s*["“‘\'](.*)["”’\']\s*$', re.DOTALL)
_LEAD_BULLET_RE = re.compile(r"^\s*(?:[-*•]|\d+[.)])\s+")


def clean_sentence(raw: str, max_sentences: int = 2) -> str:
    """One sentence (or two) out of a chat model's completion.

    `llm.clean_completion` already strips fences, `HUMAN:` labels, "Here is
    the revised paragraph:" preambles and trailing commentary; this adds the
    three failures specific to asking for a *single sentence*: the model
    wrapping the answer in quotation marks, prefixing it with a list bullet,
    and carrying on into the rest of the paragraph. `max_sentences` is 2
    rather than 1 because "Split it into two sentences of very different
    lengths" is one of `SENTENCE_MOVES` and truncating it to one would silently
    delete half the content the gate then blames the model for losing.
    """
    text = llm_mod.clean_completion(raw or "")
    text = text.strip()
    if not text:
        return ""
    # First non-empty line: a chat model that keeps going usually does it
    # after a newline, and a legitimate single sentence never contains one.
    for line in text.split("\n"):
        if line.strip():
            text = line.strip()
            break
    text = _LEAD_BULLET_RE.sub("", text)
    m = _QUOTE_WRAP_RE.match(text)
    if m and '"' not in m.group(1) and "”" not in m.group(1):
        text = m.group(1).strip()
    sentences = split_sentences(text)
    if len(sentences) > max_sentences:
        text = " ".join(sentences[:max_sentences])
    return " ".join(text.split()).strip()


def sentence_max_tokens(sentence: str, headroom: float = 1.9) -> int:
    """Generation cap for one sentence.

    `llm.estimate_max_tokens` floors at 96, which is right for a paragraph and
    three times too generous for a sentence: at beam 3 x 4 samples the floor is
    paid 12 times a step and `batch_generate` decodes until the *longest*
    stream in the batch finishes. Floored at 28 so a short sentence can still
    be split in two, capped at 200.
    """
    n_words = len(sentence.split())
    return int(max(28, min(200, n_words * 1.35 * headroom)))


# ----------------------------------------------------------------- the guide


def guide_context(
    prefix: str,
    candidate: str,
    remaining: Sequence[str] = (),
    mode: str = GuideContext.FULL,
) -> str:
    """The exact string handed to the guide detector for one candidate.

    Pure, so the choice of context is testable without a detector. See
    `GuideContext` for why `FULL` is the default.
    """
    if mode == GuideContext.SENTENCE:
        return candidate.strip()
    head = " ".join(p for p in (prefix.strip(), candidate.strip()) if p)
    if mode == GuideContext.PREFIX:
        return head
    tail = " ".join(s.strip() for s in remaining if s and s.strip())
    return " ".join(p for p in (head, tail) if p)


_GUIDE_CACHE: Dict[Tuple[str, str], Any] = {}


def clear_guide_cache() -> None:
    """Forget the guide wrappers. Their weights live in `detectors.local`'s
    cache and are freed by `local.clear_model_cache()`; this drops the last
    references to them so that release actually takes effect."""
    _GUIDE_CACHE.clear()


def _guide_detector(model_name: str = GUIDE_MODEL) -> Any:
    """The process-wide guide, built on first use.

    Imported inside the function for the reason `pipeline._detector` documents:
    `humanizer.humanize` must import on a machine with no torch.
    `score_sentences=False` because only the document score is ever read, and
    per-sentence rows cost roughly 5x -- which would defeat the entire point of
    picking a 33M guide.
    """
    key = ("guide", model_name)
    if key not in _GUIDE_CACHE:
        from ..detectors.local import ModernDetector

        _GUIDE_CACHE[key] = ModernDetector(
            model_name=model_name, head=GUIDE_HEAD, score_sentences=False
        )
    return _GUIDE_CACHE[key]


def _yardstick() -> Any:
    """The document-level verdict: `detectors.yardstick.resolve()`.

    The *same object* `pipeline.py` reports against, so the two engines cannot
    disagree about what the yardstick is. GPTZero when a key is configured;
    otherwise the local proxy, labelled as such in the response.
    """
    return pipeline_mod._yardstick()


def _finalist_scorer() -> Any:
    """The local proxy that ranks finalists. `pipeline._detector()`, reused.

    Finalists are paragraph-sized and there are several per paragraph; scoring
    them with a remote paid yardstick would cost money per candidate and fail
    GPTZero's 250-character floor on short paragraphs. So finalists are ranked
    locally and only the assembled document is judged by the yardstick.
    """
    return pipeline_mod._detector()


def yardstick_model() -> str:
    """The yardstick's display name, resolved at call time."""
    try:
        y = _yardstick()
        return y.model if y.kind == "gptzero" else y.model
    except Exception:  # noqa: BLE001
        return YARDSTICK_MODEL


def _score_with(detector: Any, text: str) -> Optional[float]:
    """`pipeline._score`, reused. `None` when the model cannot run."""
    return pipeline_mod._score(text, detector)


# ------------------------------------------------------------------ records


@dataclass
class SentenceCandidate:
    """One proposed rewrite of one source sentence, with everything measured.

    `guide_score` is the guide's, always, and is never copied into a field
    named `ai_probability`. There is no per-sentence yardstick score because
    running desklib per sentence per beam is 161 ms x beam x samples x
    sentences, which is the whole time budget for one paragraph.
    """

    step: int
    parent: int
    index: int
    text: str
    move: str = ""
    temperature: float = 0.0
    guide_score: Optional[float] = None
    gates: List[str] = field(default_factory=list)
    #: True when every candidate at this step failed and the source sentence
    #: was used verbatim instead.
    fallback: bool = False

    @property
    def passed(self) -> bool:
        return not self.gates

    def as_dict(self) -> Dict[str, Any]:
        return {
            "step": self.step,
            "parent": self.parent,
            "index": self.index,
            "text": self.text,
            "move": self.move,
            "temperature": self.temperature,
            "guide_score": None
            if self.guide_score is None
            else round(self.guide_score, 6),
            "gates": list(self.gates),
            "passed": self.passed,
            "fallback": self.fallback,
        }


@dataclass
class Hypothesis:
    """One live path through the beam: the sentences chosen so far.

    `guide_score` is the guide's score of the whole hypothesis in context at
    the step that produced it, which is what the beam is ordered by.
    `origin` traces which hypothesis of the previous step this extended, so
    the beam's bookkeeping is inspectable rather than a claim in a docstring.
    """

    sentences: Tuple[str, ...] = ()
    guide_score: Optional[float] = None
    origin: Tuple[int, ...] = ()
    n_fallbacks: int = 0

    @property
    def text(self) -> str:
        return " ".join(s.strip() for s in self.sentences if s.strip())

    def extend(
        self, sentence: str, guide_score: Optional[float], parent: int, fallback: bool
    ) -> "Hypothesis":
        return Hypothesis(
            sentences=self.sentences + (sentence,),
            guide_score=guide_score,
            origin=self.origin + (parent,),
            n_fallbacks=self.n_fallbacks + (1 if fallback else 0),
        )

    def as_dict(self) -> Dict[str, Any]:
        return {
            "text": self.text,
            "n_sentences": len(self.sentences),
            "guide_score": None
            if self.guide_score is None
            else round(self.guide_score, 6),
            "origin": list(self.origin),
            "n_fallbacks": self.n_fallbacks,
        }


def select_beam(
    scored: Sequence[Tuple[Optional[float], int, Hypothesis]],
    width: int,
) -> List[Hypothesis]:
    """Keep the `width` best hypotheses. Pure, so the bookkeeping is testable.

    `scored` is `(guide_score, tiebreak, hypothesis)`. Ordering rules, in
    order:

    1. Duplicate texts collapse to their first occurrence. Without this a
       sentence the model rewrites identically from three beams eats the whole
       beam, and the search silently becomes greedy.
    2. Unscored hypotheses (`guide_score is None`, i.e. no guide installed)
       sort after scored ones but are still kept, so a run without the guide
       degrades to "first `width` candidates" instead of returning nothing.
    3. Ties break on `tiebreak` ascending, which callers set to the candidate's
       generation index. Lower index means a cooler temperature and a more
       conservative structural move, so a tie resolves toward the safer edit.

    Raises:
        ValueError: when `width` is not positive.
    """
    if width <= 0:
        raise ValueError("width must be positive")
    seen: Dict[str, bool] = {}
    unique: List[Tuple[Optional[float], int, Hypothesis]] = []
    for score, tiebreak, hyp in scored:
        key = hyp.text.strip()
        if key in seen:
            continue
        seen[key] = True
        unique.append((score, tiebreak, hyp))
    unique.sort(
        key=lambda row: (
            row[0] is None,
            row[0] if row[0] is not None else 0.0,
            row[1],
        )
    )
    return [hyp for _score, _tb, hyp in unique[:width]]


# ------------------------------------------------------------------- gates


def sentence_gate(
    source_sentence: str,
    candidate: str,
    min_overlap: float = 0.45,
    max_length_ratio_delta: float = 0.75,
) -> List[str]:
    """Names of every per-sentence gate the candidate fails.

    The *same* invariant test the paragraph gate runs, applied one sentence
    earlier. `pipeline._invariant_failures` is called directly rather than
    copied: numbers, dates, quotations and citations are compared as exact
    multisets and every capitalised run in the source must survive verbatim.

    The two thresholds differ from the paragraph gate's on purpose and the
    difference is a loosening, not a hole:

    * `max_length_ratio_delta` is 0.75 against the paragraph's 0.25 because
      "Make it short and blunt" and "Let it run long" are two of eight
      `SENTENCE_MOVES` and both are exactly the sentence-length variance the
      rewrite is *for* (research/10: human sentence-length CV 0.42-0.60,
      AI 0.23). The paragraph-level ratio gate still runs afterwards on the
      assembled text, so total length cannot drift.
    * `min_overlap` is per sentence, where a single dropped noun is a much
      larger share of the content words than it is in a paragraph.

    Nothing here can let a paragraph through that
    `pipeline._gate_candidate` would reject: this runs *in addition to* it,
    never instead of it.
    """
    text = (candidate or "").strip()
    if not text:
        return ["empty"]
    n_source = len(words(source_sentence))
    n_candidate = len(words(text))
    if n_source == 0:
        return ["empty_source"]
    failures: List[str] = []
    ratio = n_candidate / n_source
    if abs(ratio - 1.0) > max_length_ratio_delta:
        failures.append("length_ratio")
    if content_overlap(source_sentence, text) < min_overlap:
        failures.append("content_drift")
    for name in pipeline_mod._invariant_failures(source_sentence, text):
        failures.append("invariant:" + name)
    return failures


# ------------------------------------------------------- token-level guidance


def reweight_logprobs(
    logprobs: Sequence[float],
    guide_scores: Sequence[Optional[float]],
    strength: float = 4.0,
) -> List[float]:
    """Bias a next-token distribution away from the guide's AI signal.

    The published method (research/05 §1.2) takes the argmax of the guide over
    the top-k candidate tokens, i.e. it discards the LM's own distribution
    entirely at every step. That is variant B at `strength=inf`, and it is
    measurably worse for text quality: it drives perplexity up and, with a weak
    guide, walks straight off the manifold. So this is a soft version --

        logprob'_i = logprob_i - strength * (guide_i - min(guide))

    -- which leaves the LM's ranking intact where the guide is indifferent and
    only overrides it where the guide separates the candidates. `strength=0`
    reproduces plain sampling exactly, which is the control this needs to have.

    Candidates the guide could not score keep their original logprob, so a
    guide failure degrades to ordinary sampling rather than to a uniform
    distribution over the top-k.

    Returns:
        A new list, same length and order as `logprobs`.

    Raises:
        ValueError: on a length mismatch, which would silently mis-attribute
            every score to the wrong token.
    """
    if len(logprobs) != len(guide_scores):
        raise ValueError(
            "logprobs and guide_scores must be the same length (%d vs %d)"
            % (len(logprobs), len(guide_scores))
        )
    finite = [g for g in guide_scores if g is not None and math.isfinite(g)]
    if not finite or strength == 0.0:
        return [float(lp) for lp in logprobs]
    floor = min(finite)
    out: List[float] = []
    for lp, g in zip(logprobs, guide_scores):
        if g is None or not math.isfinite(g):
            out.append(float(lp))
        else:
            out.append(float(lp) - float(strength) * (float(g) - floor))
    return out


# ------------------------------------------------------------------- config


@dataclass
class GuidedConfig:
    """Everything tunable about one guided run.

    The defaults are sized to the 30-second budget from measurements on an M4
    Pro: `batch_generate` of 12 short prompts on Qwen2.5-3B-Instruct-4bit runs
    ~2.0 s, the guide adds 12 x 28 ms = 0.34 s, so a 9-sentence paragraph is
    ~21 s and a second paragraph will overrun -- which `time_budget_s` catches
    between sentences, not mid-batch.

    The gate field names are `pipeline.PipelineConfig`'s, verbatim, so this
    object can be passed straight to `pipeline._gate_candidate`. That is the
    reuse, not a coincidence.
    """

    #: Live hypotheses carried between sentences. 1 is greedy; past 4 the
    #: batch stops fitting the budget. research/08 §1.5 (Stroebl et al.):
    #: with an imperfect verifier "optimal sampling attempts are often fewer
    #: than 10", and beam x samples is that count.
    beam_width: int = 3
    #: Continuations proposed per hypothesis per sentence.
    n_samples: int = 4
    mode: str = GuideMode.SEGMENT
    guide_context: str = GuideContext.FULL
    #: Guide every m tokens in `GuideMode.TOKEN`. At m=1 a 60-token sentence
    #: with k=8 is ~13 s of guide calls alone, so m=1 is not a usable setting
    #: and the default is not close to it.
    guidance_interval: int = 8
    #: Top-k next tokens scored at each guided step in `GuideMode.TOKEN`.
    top_k: int = 8
    #: See `reweight_logprobs`.
    guidance_strength: float = 4.0
    aggressiveness: str = "strong"
    time_budget_s: float = 30.0
    #: `pipeline.OBJECTIVE_EVADE` (default) or `OBJECTIVE_FAITHFUL`. Sets the
    #: three gate values below when they are left as `None`; see
    #: `pipeline.GATE_PRESETS`.
    objective: str = pipeline_mod.OBJECTIVE_EVADE
    #: Per-sentence content floor. See `sentence_gate`. `None` follows the
    #: objective: 0.30 under `evade`, 0.45 under `faithful`.
    min_sentence_overlap: Optional[float] = None
    #: --- names below are `PipelineConfig`'s and are read by its gate ---
    #: Author-vouched names, dates and figures; see `PipelineConfig.facts`.
    #: The guided prompts do not use it (a sentence-level continuation adds
    #: no particulars), but the paragraph gate honours it, so a run with the
    #: same facts as an LLM run judges candidates by the same rule.
    facts: str = ""
    min_content_overlap: Optional[float] = None
    max_length_ratio_delta: Optional[float] = None
    min_length_ratio: Optional[float] = None
    model: Optional[str] = None
    guide_model: str = GUIDE_MODEL

    def __post_init__(self) -> None:
        if self.objective not in pipeline_mod.GATE_PRESETS:
            raise ValueError(
                "objective must be one of %s"
                % ", ".join(sorted(pipeline_mod.GATE_PRESETS))
            )
        preset = pipeline_mod.GATE_PRESETS[self.objective]
        if self.min_content_overlap is None:
            self.min_content_overlap = preset["min_content_overlap"]
        if self.max_length_ratio_delta is None:
            self.max_length_ratio_delta = preset["max_length_ratio_delta"]
        if self.min_length_ratio is None:
            self.min_length_ratio = preset["min_length_ratio"]
        if self.min_sentence_overlap is None:
            self.min_sentence_overlap = preset["min_content_overlap"]

    def resolved_model(self) -> str:
        return self.model or llm_mod.DEFAULT_MODEL

    def validate(self) -> None:
        """Raise `ValueError` on a configuration that cannot run."""
        if self.beam_width <= 0:
            raise ValueError("beam_width must be positive")
        if self.n_samples <= 0:
            raise ValueError("n_samples must be positive")
        if self.mode not in GuideMode.ALL:
            raise ValueError("mode must be one of %s" % (GuideMode.ALL,))
        if self.guide_context not in GuideContext.ALL:
            raise ValueError("guide_context must be one of %s" % (GuideContext.ALL,))
        if self.guidance_interval <= 0:
            raise ValueError("guidance_interval must be positive")
        if self.top_k <= 0:
            raise ValueError("top_k must be positive")

    @property
    def fanout(self) -> int:
        """Generations per sentence step. The thing the budget is spent on."""
        return self.beam_width * self.n_samples


@dataclass
class GuidedParagraph:
    """What happened to one paragraph."""

    index: int
    original: str
    chosen: str
    ai_probability_before: Optional[float] = None
    ai_probability_after: Optional[float] = None
    guide_probability_before: Optional[float] = None
    guide_probability_after: Optional[float] = None
    n_sentences: int = 0
    n_fallback_sentences: int = 0
    steps: List[List[SentenceCandidate]] = field(default_factory=list)
    finalists: List[Dict[str, Any]] = field(default_factory=list)
    #: The finalists as live objects, for the scrub and verify stages. Not
    #: serialised -- `finalists` above is the wire form. Declared as a field
    #: rather than stapled on as an ad-hoc attribute so it survives a future
    #: `slots=True` and shows up in the dataclass rather than in a traceback.
    finalist_objects: List["Hypothesis"] = field(default_factory=list, repr=False)
    gates: List[str] = field(default_factory=list)
    fallback_reason: Optional[str] = None
    quality: Dict[str, Any] = field(default_factory=dict)

    @property
    def changed(self) -> bool:
        return self.chosen.strip() != self.original.strip()

    def as_dict(self, with_candidates: bool = True) -> Dict[str, Any]:
        payload: Dict[str, Any] = {
            "index": self.index,
            "original": self.original,
            "humanized": self.chosen,
            "ai_probability_before": self.ai_probability_before,
            "ai_probability_after": self.ai_probability_after,
            "guide_probability_before": self.guide_probability_before,
            "guide_probability_after": self.guide_probability_after,
            "n_sentences": self.n_sentences,
            "n_fallback_sentences": self.n_fallback_sentences,
            "changed": self.changed,
            "gates": list(self.gates),
            "fallback_reason": self.fallback_reason,
            "quality": self.quality,
            "finalists": self.finalists,
        }
        if with_candidates:
            payload["steps"] = [
                [c.as_dict() for c in step] for step in self.steps
            ]
        return payload


@dataclass
class GuidedResult:
    """The full result. `as_dict()` is the HTTP response body."""

    original: str
    humanized: str
    model: str
    backend: str = ""
    before: Dict[str, Any] = field(default_factory=dict)
    after: Dict[str, Any] = field(default_factory=dict)
    guide: Dict[str, Any] = field(default_factory=dict)
    summary: Dict[str, Any] = field(default_factory=dict)
    paragraphs: List[GuidedParagraph] = field(default_factory=list)
    stages: List[Dict[str, Any]] = field(default_factory=list)

    @property
    def changed(self) -> bool:
        return self.humanized != self.original

    def as_dict(self) -> Dict[str, Any]:
        """The `POST /api/humanize/guided` body.

        `original`, `humanized`, `edits`, `before`, `after`, `summary`,
        `model`, `backend`, `stages` mean exactly what they mean on
        `POST /api/humanize/llm`, so a client that renders one renders the
        other. `edits` is always empty: a sentence-by-sentence regeneration is
        not expressible as a span edit list and inventing one would be a lie.
        Diff `paragraphs[i].original` against `paragraphs[i].humanized`.

        `guide` is the addition, and it is separate from `before`/`after` for
        the reason the module docstring gives: it is the search heuristic's
        opinion, not a measurement. `summary["guide_transfer"]` reports how far
        the two disagreed on this run.
        """
        return {
            "original": self.original,
            "humanized": self.humanized,
            "edits": [],
            "before": self.before,
            "after": self.after,
            "guide": self.guide,
            "summary": self.summary,
            "model": self.model,
            "backend": self.backend,
            "stages": list(self.stages),
            "paragraphs": [p.as_dict() for p in self.paragraphs],
        }


# ------------------------------------------------------------- availability


def guided_available() -> bool:
    """Whether guided decoding can run at all right now."""
    return llm_mod.generation_available()


def guided_unavailable_reason() -> Optional[str]:
    """A user-facing sentence naming a fallback, or None when it can run.

    Two things can be missing and they have different fallbacks, so they are
    reported separately rather than collapsed into "unavailable": no MLX means
    no generation at all (fall back to the rule-based engine), while no torch
    means no *guide* -- which is a different, weaker failure handled inside
    `stream()`, not here, because a guideless run still produces text.
    """
    return llm_mod.generation_unavailable_reason()


def guide_unavailable_reason(model_name: str = GUIDE_MODEL) -> Optional[str]:
    """Why the in-loop guide cannot run, or None. Never raises."""
    try:
        det = _guide_detector(model_name)
        if det.available():
            return None
        return det.unavailable_reason() or "the guide detector is unavailable"
    except Exception as exc:  # noqa: BLE001 - availability must not raise
        return "%s: %s" % (type(exc).__name__, exc)


# ------------------------------------------------------------------- helpers


def _paragraph_segments(text: str) -> List[str]:
    """Paragraphs, or the whole document as one when it has no blank lines."""
    parts = split_paragraphs(text)
    return parts or ([text.strip()] if text.strip() else [])


def _measure(text: str, detector: Any) -> Dict[str, Any]:
    """The `before`/`after` block. The probability is the yardstick's."""
    doc = Document.parse(text)
    probability = _score_with(detector, text)
    return {
        "ai_probability": probability,
        "label": pipeline_mod._label(probability),
        "features": extract_from_document(doc),
    }


def _quality(source: str, candidate: str) -> Dict[str, Any]:
    """Readability, shape and vocabulary numbers. `pipeline._quality`, reused."""
    return pipeline_mod._quality(source, candidate)


def _plural(n: int, word: str) -> str:
    return "%d %s%s" % (n, word, "" if n == 1 else "s")


def _transfer(rows: Sequence[Tuple[Optional[float], Optional[float]]]) -> Dict[str, Any]:
    """Guide-versus-yardstick agreement over `(guide, yardstick)` pairs.

    research/08 §3.2 is the reason this is computed and reported rather than
    assumed: transfer between detectors is "real but wildly uneven", a 34-point
    spread inside a single paper, so "a mean improvement number is actively
    misleading". What is reported here is the raw disagreement -- mean signed
    gap, mean absolute gap, and how often the two land on opposite sides of
    0.5 -- because that, not a correlation coefficient over five points, is
    what tells a reader whether the search was optimising anything real.
    """
    pairs = [
        (float(g), float(y))
        for g, y in rows
        if g is not None and y is not None and math.isfinite(g) and math.isfinite(y)
    ]
    if not pairs:
        return {
            "n": 0,
            "mean_guide": None,
            "mean_yardstick": None,
            "mean_signed_gap": None,
            "mean_abs_gap": None,
            "verdict_disagreements": None,
            "note": "no paragraph was scored by both the guide and the yardstick",
        }
    n = len(pairs)
    mean_g = sum(g for g, _ in pairs) / n
    mean_y = sum(y for _, y in pairs) / n
    signed = sum(g - y for g, y in pairs) / n
    absolute = sum(abs(g - y) for g, y in pairs) / n
    disagree = sum(
        1 for g, y in pairs if (g >= AI_THRESHOLD) != (y >= AI_THRESHOLD)
    )
    return {
        "n": n,
        "mean_guide": round(mean_g, 6),
        "mean_yardstick": round(mean_y, 6),
        "mean_signed_gap": round(signed, 6),
        "mean_abs_gap": round(absolute, 6),
        "verdict_disagreements": disagree,
        "note": (
            "guide = %s (search heuristic); yardstick = %s (the reported "
            "number). A large gap means the search was optimising something "
            "the yardstick does not measure -- research/08 §3.2."
            % (GUIDE_MODEL, YARDSTICK_MODEL)
        ),
    }


# ------------------------------------------------------------- the search


def _search_paragraph(
    source: str,
    cfg: GuidedConfig,
    backend: llm_mod.Backend,
    guide: Any,
    emit: Callable[[float, str], ProgressEvent],
    deadline: Optional[float] = None,
) -> Iterator[ProgressEvent]:
    """Variant A. Beam search over sentences, ordered by the guide.

    A **generator**, not a function returning a tuple, and deliberately so: a
    paragraph's search is the 20-30 seconds a user spends staring at the
    progress bar, and a callback that buffers its events until the search
    finishes would render as a frozen `generate` stage followed by every
    event at once. `stream()` consumes it with `yield from`, which forwards
    each event the instant it is produced and delivers the search's
    `return` value as the expression result.

    Returns (via `StopIteration.value`, i.e. the `yield from` expression)
    `(finalists, steps, stats)`. `finalists` is the surviving beam,
    best first. `steps[i]` is every candidate considered at sentence `i`,
    including the ones the gate rejected, so the response can show the search
    rather than assert it.

    The loop, per source sentence:

    1. Every live hypothesis proposes `n_samples` continuations. All
       `beam_width x n_samples` prompts go to the backend in **one** call, so
       `MlxBackend` batches them (measured: 12 short prompts in ~2.0 s against
       ~7 s looped).
    2. Each completion is cleaned to a sentence and run through
       `sentence_gate`. Failures are recorded and dropped.
    3. Survivors are scored by the guide in `cfg.guide_context`.
    4. `select_beam` keeps the best `beam_width`.
    5. If *nothing* survives, every hypothesis extends with the source sentence
       verbatim. That is the honest failure: the paragraph keeps its meaning
       and the fallback is counted in `n_fallback_sentences`.

    The time budget is checked between sentences. A paragraph that runs out
    keeps the source's remaining sentences, which is why an overrun degrades
    into a partial rewrite rather than a truncated one.
    """
    sentences = split_sentences(source)
    if not sentences:
        sentences = [source.strip()]
    moves = sentence_moves(cfg.n_samples)

    beam: List[Hypothesis] = [Hypothesis()]
    steps: List[List[SentenceCandidate]] = []
    gen_seconds = 0.0
    gen_tokens = 0
    guide_calls = 0
    guide_seconds = 0.0
    batched = False
    budget_stop_at: Optional[int] = None

    for i, src_sentence in enumerate(sentences):
        if deadline is not None and time.perf_counter() > deadline and i > 0:
            budget_stop_at = i
            yield emit(
                i / len(sentences),
                "budget spent at sentence %d of %d; the rest is kept as written"
                % (i + 1, len(sentences)),
            )
            break

        following = sentences[i + 1] if i + 1 < len(sentences) else ""
        remaining = sentences[i + 1 :]
        requests: List[llm_mod.GenerationRequest] = []
        routing: List[Tuple[int, int]] = []
        for b, hyp in enumerate(beam):
            for j, (move, temperature) in enumerate(moves):
                requests.append(
                    llm_mod.GenerationRequest(
                        prompt=build_sentence_prompt(
                            hyp.text, src_sentence, move, following
                        ),
                        temperature=temperature,
                        max_tokens=sentence_max_tokens(src_sentence),
                        tag=(i, b, j),
                    )
                )
                routing.append((b, j))

        yield emit(
            i / len(sentences),
            "sentence %d of %d, %d beam x %d samples = %s"
            % (
                i + 1,
                len(sentences),
                len(beam),
                cfg.n_samples,
                _plural(len(requests), "continuation"),
            ),
        )
        batch = backend.generate(requests)
        gen_seconds += batch.seconds
        gen_tokens += batch.generation_tokens
        batched = batched or batch.batched

        step_records: List[SentenceCandidate] = []
        scored: List[Tuple[Optional[float], int, Hypothesis]] = []
        for n, ((b, j), raw) in enumerate(zip(routing, batch.texts)):
            move, temperature = moves[j]
            text = clean_sentence(raw)
            record = SentenceCandidate(
                step=i,
                parent=b,
                index=j,
                text=text,
                move=move,
                temperature=temperature,
            )
            record.gates = sentence_gate(
                src_sentence,
                text,
                min_overlap=cfg.min_sentence_overlap,
            )
            if record.passed:
                if guide is not None:
                    context = guide_context(
                        beam[b].text, text, remaining, cfg.guide_context
                    )
                    t0 = time.perf_counter()
                    record.guide_score = _score_with(guide, context)
                    guide_seconds += time.perf_counter() - t0
                    guide_calls += 1
                extended = beam[b].extend(text, record.guide_score, b, False)
                scored.append((record.guide_score, n, extended))
            step_records.append(record)

        if scored:
            beam = select_beam(scored, cfg.beam_width)
        else:
            # Nothing survived. Keep meaning, count the failure, carry on.
            # `guide_score=None` rather than the source sentence's own score:
            # a fallback is not a search result and must not be ranked as one.
            beam = [
                hyp.extend(src_sentence, None, b, True)
                for b, hyp in enumerate(beam)
            ]
            step_records.append(
                SentenceCandidate(
                    step=i,
                    parent=-1,
                    index=-1,
                    text=src_sentence,
                    move="(source sentence kept)",
                    fallback=True,
                )
            )
        steps.append(step_records)

    if budget_stop_at is not None:
        tail = sentences[budget_stop_at:]
        beam = [
            Hypothesis(
                sentences=hyp.sentences + tuple(tail),
                guide_score=hyp.guide_score,
                origin=hyp.origin + tuple(-1 for _ in tail),
                n_fallbacks=hyp.n_fallbacks + len(tail),
            )
            for hyp in beam
        ]

    stats = {
        "n_sentences": len(sentences),
        "generation_seconds": gen_seconds,
        "generation_tokens": gen_tokens,
        "guide_calls": guide_calls,
        "guide_seconds": guide_seconds,
        "batched": batched,
        "budget_truncated": budget_stop_at is not None,
    }
    return beam, steps, stats


# --------------------------------------------------- variant B: token level


def _eos_ids(tokenizer: Any) -> frozenset:
    """Every id that ends a turn for this tokenizer. Empty is survivable."""
    ids = set()
    for attr in ("eos_token_ids", "eos_token_id"):
        value = getattr(tokenizer, attr, None)
        if isinstance(value, int):
            ids.add(value)
        elif isinstance(value, (list, tuple, set, frozenset)):
            ids.update(int(v) for v in value)
    return frozenset(ids)


def token_guided_sentence(
    backend: Any,
    prompt: llm_mod.Prompt,
    temperature: float,
    max_tokens: int,
    cfg: GuidedConfig,
    guide: Any,
    prefix_text: str = "",
    remaining: Sequence[str] = (),
) -> Tuple[str, Dict[str, Any]]:
    """Variant B: decode one sentence with the guide inside the sampler.

    The published algorithm (research/05 §1.2) with one measured concession:
    the guide runs every `cfg.guidance_interval` tokens, not every token. At
    m=1, k=8 and 28 ms a call, a 60-token sentence costs 13.4 s of guide
    forward passes *before* any generation -- roughly half the entire budget
    for one sentence of one paragraph. m is a latency knob and the number is
    reported (`guided_steps`, `guide_calls`) rather than hidden.

    At a guided step: take the LM's top-`cfg.top_k` next tokens, decode each
    onto the text produced so far, score each with the guide in
    `cfg.guide_context`, reweight the logprobs with `reweight_logprobs` and
    sample from the reweighted top-k. At every other step the ordinary
    `mlx_lm` sampler runs untouched.

    Returns:
        `(text, stats)`. `stats` carries `guide_calls`, `guide_seconds`,
        `guided_steps`, `tokens` and `seconds`.

    Raises:
        RuntimeError: when MLX is not importable. Callers in this module catch
            it and fall back to `GuideMode.SEGMENT`, naming the reason.
    """
    try:
        import mlx.core as mx
        import numpy as np
        from mlx_lm.generate import generate_step
        from mlx_lm.sample_utils import make_sampler
    except Exception as exc:  # noqa: BLE001
        raise RuntimeError(
            "token-level guidance needs mlx and numpy: %s. "
            "Use mode='segment', which needs neither." % exc
        ) from exc

    backend.load()
    model = getattr(backend, "_model", None)
    tokenizer = getattr(backend, "_tokenizer", None)
    if model is None or tokenizer is None:
        raise RuntimeError(
            "token-level guidance needs an MLX backend with a loaded model; "
            "%r exposes none. Use mode='segment'." % getattr(backend, "name", backend)
        )

    base_sampler = make_sampler(temp=float(temperature), top_p=0.99)
    produced: List[int] = []
    stats = {
        "guide_calls": 0,
        "guide_seconds": 0.0,
        "guided_steps": 0,
        "tokens": 0,
        "seconds": 0.0,
    }
    step = [0]
    remaining_text = " ".join(s.strip() for s in remaining if s and s.strip())

    def sampler(logprobs):
        n = step[0]
        step[0] = n + 1
        if (
            guide is None
            or cfg.guidance_strength == 0.0
            or n % cfg.guidance_interval != 0
        ):
            return base_sampler(logprobs)
        row = logprobs[0] if getattr(logprobs, "ndim", 1) > 1 else logprobs
        arr = np.asarray(row, dtype=np.float64)
        k = int(min(cfg.top_k, arr.shape[-1]))
        top = np.argpartition(-arr, k - 1)[:k]
        top = top[np.argsort(-arr[top])]
        scores: List[Optional[float]] = []
        for tid in top:
            piece = tokenizer.decode(produced + [int(tid)])
            context = guide_context(
                prefix_text, piece, [remaining_text], cfg.guide_context
            )
            t0 = time.perf_counter()
            scores.append(_score_with(guide, context))
            stats["guide_seconds"] += time.perf_counter() - t0
            stats["guide_calls"] += 1
        adjusted = reweight_logprobs(
            [float(arr[int(t)]) for t in top], scores, cfg.guidance_strength
        )
        stats["guided_steps"] += 1
        z = np.asarray(adjusted, dtype=np.float64) / max(1e-6, float(temperature))
        z = z - z.max()
        weights = np.exp(z)
        total = float(weights.sum())
        if not math.isfinite(total) or total <= 0.0:
            return base_sampler(logprobs)
        choice = int(np.random.choice(len(top), p=weights / total))
        return mx.array([int(top[choice])])

    eos = _eos_ids(tokenizer)
    started = time.perf_counter()
    prompt_tokens = mx.array(backend._encode(prompt))
    for token, _lp in generate_step(
        prompt_tokens, model, max_tokens=int(max_tokens), sampler=sampler
    ):
        tid = int(token.item() if hasattr(token, "item") else token)
        if tid in eos:
            break
        produced.append(tid)
    stats["tokens"] = len(produced)
    stats["seconds"] = time.perf_counter() - started
    return tokenizer.decode(produced), stats


class TokenGuidedBackend(llm_mod.Backend):
    """Adapts `token_guided_sentence` to the `llm.Backend` interface.

    Wrapping rather than branching inside `_search_paragraph` keeps variant B
    a drop-in for variant A's inner loop: the beam search, the gates, the
    fallbacks and the event stream are identical, and the only difference is
    where the guide is consulted. It also means variant B inherits variant A's
    beam for free, which the published depth-1 method does not have.

    It cannot batch -- the guide has to see one partial sequence at a time --
    so `batched` is False and each request is decoded in turn. That is the
    measured cost of the finer control, and it is why `GuideMode.TOKEN` is not
    the default.
    """

    name = "mlx-token-guided"

    def __init__(self, inner: Any, cfg: GuidedConfig, guide: Any):
        self.inner = inner
        self.cfg = cfg
        self.guide = guide
        self.model_name = getattr(inner, "model_name", "")
        self.stats = {"guide_calls": 0, "guide_seconds": 0.0, "guided_steps": 0}

    def available(self) -> bool:
        return self.inner.available()

    def unavailable_reason(self) -> Optional[str]:
        return self.inner.unavailable_reason()

    def load(self) -> None:
        self.inner.load()

    def generate(
        self, requests: Sequence[llm_mod.GenerationRequest]
    ) -> llm_mod.GenerationBatch:
        requests = list(requests)
        started = time.perf_counter()
        texts: List[str] = []
        tokens = 0
        for req in requests:
            text, stats = token_guided_sentence(
                self.inner,
                req.prompt,
                req.temperature,
                req.max_tokens,
                self.cfg,
                self.guide,
            )
            texts.append(text)
            tokens += int(stats["tokens"])
            for key in ("guide_calls", "guided_steps"):
                self.stats[key] += int(stats[key])
            self.stats["guide_seconds"] += float(stats["guide_seconds"])
        seconds = time.perf_counter() - started
        return llm_mod.GenerationBatch(
            texts=texts,
            seconds=seconds,
            generation_tokens=tokens,
            tokens_per_second=(tokens / seconds) if seconds > 0 else 0.0,
            batched=False,
            backend=self.name,
            model=self.model_name,
        )


# ------------------------------------------------------------------ the run


def stream(
    text: str,
    config: Optional[GuidedConfig] = None,
    backend: Optional[llm_mod.Backend] = None,
    detector: Any = None,
    guide: Any = None,
) -> Iterator[ProgressEvent]:
    """Run detector-guided decoding, yielding a `ProgressEvent` per step.

    Args:
        text: the document. Normalised on entry.
        config: see `GuidedConfig`. `None` uses the defaults.
        backend: an `llm.Backend`. `None` builds `llm.default_backend`. Tests
            pass `llm.EchoBackend`.
        detector: **the yardstick.** Anything with
            `.score(text).ai_probability`. `None` uses the process-wide
            desklib `ModernDetector` -- the same instance `pipeline.py` uses.
            Pass `False` to score nothing.
        guide: **the in-loop search heuristic**, a separate object from
            `detector` and never a substitute for it. `None` builds the
            e5-small guide. Pass `False` to run the beam search unguided,
            which is the control this module needs to have: an unguided run
            with the same beam and the same gates isolates how much of any
            movement came from the guide rather than from resampling.

    Yields:
        `ProgressEvent`s in `STAGES` order. The final one is `finalize/done`
        and carries `result`.

    Raises:
        ValueError: on empty input or an invalid config.
        RuntimeError: when the generation backend cannot load. The message
            names the fallback.
    """
    if not text or not text.strip():
        raise ValueError("text must not be empty")
    cfg = config or GuidedConfig()
    cfg.validate()

    clock = pipeline_mod._Clock()
    stage_timings: List[Dict[str, Any]] = []
    stage_started: Dict[str, float] = {}

    def event(
        stage: str,
        status: str,
        progress: float,
        detail: str,
        result: Optional[Dict[str, Any]] = None,
    ) -> ProgressEvent:
        now = clock()
        if status == "start":
            stage_started[stage] = now
        if status in ("done", "skip"):
            started = stage_started.pop(stage, now)
            stage_timings.append(
                {
                    "stage": stage,
                    "status": status,
                    "seconds": round(now - started, 3),
                    "detail": detail,
                    "round": 1,
                }
            )
        return ProgressEvent(stage, status, progress, detail, now, 1, result)

    if detector is False:
        yardstick = None
        finalist_scorer = None
    elif detector is None:
        yardstick = _yardstick()
        finalist_scorer = _finalist_scorer()
    else:
        yardstick = detector
        finalist_scorer = detector
    yardstick_name = (
        yardstick.model
        if isinstance(yardstick, yardstick_mod.Yardstick)
        else (pipeline_mod._scorer_name(yardstick) if yardstick is not None else "nothing")
    )
    guide_reason: Optional[str] = None
    if guide is False:
        guide_obj = None
        guide_reason = "guide disabled by the caller; the beam search is unguided"
    elif guide is None:
        guide_obj = _guide_detector(cfg.guide_model)
        guide_reason = guide_unavailable_reason(cfg.guide_model)
        if guide_reason is not None:
            guide_obj = None
    else:
        guide_obj = guide

    if backend is None:
        backend = llm_mod.default_backend("faithful", cfg.model)

    # -- analyze ----------------------------------------------------------
    yield event("analyze", "start", 0.0, "reading the document")
    original = normalize(text)
    segments = _paragraph_segments(original)
    doc = Document.parse(original)
    yield event(
        "analyze",
        "progress",
        0.4,
        "%s, %s, %s"
        % (
            _plural(len(segments), "paragraph"),
            _plural(doc.n_sentences, "sentence"),
            _plural(doc.n_words, "word"),
        ),
    )
    before = _measure(original, yardstick)
    p_before = before["ai_probability"]
    guide_before = _score_with(guide_obj, original)
    yield event(
        "analyze",
        "done",
        1.0,
        "scored the original with %s: %s"
        % (
            yardstick_name,
            "detector unavailable"
            if p_before is None
            else "p(AI) %.3f, labelled %s" % (p_before, before["label"]),
        ),
    )

    # -- plan -------------------------------------------------------------
    yield event("plan", "start", 0.0, "sizing the search")
    n_sentences = doc.n_sentences or len(segments)
    if cfg.mode == GuideMode.TOKEN and guide_obj is not None:
        try:
            backend = TokenGuidedBackend(backend, cfg, guide_obj)
        except Exception as exc:  # noqa: BLE001 - fall back, never fail
            guide_reason = (
                "token-level guidance unavailable (%s); ran segment-guided "
                "search instead" % exc
            )
            cfg.mode = GuideMode.SEGMENT
    elif cfg.mode == GuideMode.TOKEN:
        guide_reason = (guide_reason or "") + (
            " token-level guidance needs a guide; ran segment-guided search"
        )
        cfg.mode = GuideMode.SEGMENT
    yield event(
        "plan",
        "done",
        1.0,
        "%s mode, beam %d x %d samples = %s per sentence, %s, guide %s, "
        "budget %.0fs"
        % (
            cfg.mode,
            cfg.beam_width,
            cfg.n_samples,
            _plural(cfg.fanout, "continuation"),
            _plural(n_sentences, "sentence"),
            "unavailable (%s)" % guide_reason if guide_obj is None else GUIDE_ENGINE,
            cfg.time_budget_s,
        ),
    )

    outcomes = [
        GuidedParagraph(index=i, original=s, chosen=s) for i, s in enumerate(segments)
    ]
    for outcome in outcomes:
        outcome.ai_probability_before = _score_with(yardstick, outcome.original)
        outcome.guide_probability_before = _score_with(guide_obj, outcome.original)

    # -- generate ---------------------------------------------------------
    yield event("generate", "start", 0.0, "loading %s" % cfg.resolved_model())
    backend.load()

    totals = {
        "generation_seconds": 0.0,
        "generation_tokens": 0,
        "guide_calls": 0,
        "guide_seconds": 0.0,
    }
    batched = False
    deadline = clock.t0 + cfg.time_budget_s
    for n, outcome in enumerate(outcomes):
        if clock() > cfg.time_budget_s and n > 0:
            yield event(
                "generate",
                "progress",
                n / max(1, len(outcomes)),
                "budget spent after paragraph %d of %d; %d left as written"
                % (n, len(outcomes), len(outcomes) - n),
            )
            break

        def emit(fraction: float, detail: str, _n: int = n) -> ProgressEvent:
            return event(
                "generate",
                "progress",
                (_n + fraction) / max(1, len(outcomes)),
                "paragraph %d of %d, %s" % (_n + 1, len(outcomes), detail),
            )

        # `yield from` forwards each search event live and binds the search's
        # return value. A callback would buffer the whole paragraph.
        finalists, steps, stats = yield from _search_paragraph(
            outcome.original, cfg, backend, guide_obj, emit, deadline
        )
        outcome.steps = steps
        outcome.n_sentences = stats["n_sentences"]
        outcome.finalists = [h.as_dict() for h in finalists]
        outcome.n_fallback_sentences = (
            min(h.n_fallbacks for h in finalists) if finalists else 0
        )
        outcome.finalist_objects = finalists
        totals["generation_seconds"] += stats["generation_seconds"]
        totals["generation_tokens"] += stats["generation_tokens"]
        totals["guide_calls"] += stats["guide_calls"]
        totals["guide_seconds"] += stats["guide_seconds"]
        batched = batched or stats["batched"]
        yield event(
            "generate",
            "progress",
            (n + 1) / max(1, len(outcomes)),
            "paragraph %d of %d: %s survived, %d guide calls in %.1fs"
            % (
                n + 1,
                len(outcomes),
                _plural(len(finalists), "hypothesis" if len(finalists) == 1 else "hypothes"),
                stats["guide_calls"],
                stats["guide_seconds"],
            ),
        )
    if isinstance(backend, TokenGuidedBackend):
        totals["guide_calls"] += backend.stats["guide_calls"]
        totals["guide_seconds"] += backend.stats["guide_seconds"]
    yield event(
        "generate",
        "done",
        1.0,
        "%.1fs of generation, %d guide calls costing %.1fs, %s"
        % (
            totals["generation_seconds"],
            totals["guide_calls"],
            totals["guide_seconds"],
            "batched decode" if batched else "one at a time",
        ),
    )

    # -- scrub ------------------------------------------------------------
    # `pipeline._scrub`, unchanged. After the model, never before: the
    # instruct checkpoint reintroduces the vocabulary this pass removes.
    yield event("scrub", "start", 0.0, "applying deterministic transforms")
    scrubbed: Dict[int, List[str]] = {}
    n_edits = 0
    for n, outcome in enumerate(outcomes):
        finalists = outcome.finalist_objects
        texts: List[str] = []
        for hyp in finalists:
            cleaned, edits = pipeline_mod._scrub(hyp.text, cfg.aggressiveness)
            texts.append(cleaned)
            n_edits += len(edits)
        scrubbed[outcome.index] = texts
        yield event(
            "scrub",
            "progress",
            (n + 1) / max(1, len(outcomes)),
            "paragraph %d of %d, %s"
            % (n + 1, len(outcomes), _plural(len(texts), "finalist")),
        )
    yield event(
        "scrub",
        "done",
        1.0,
        "%s across %s"
        % (
            _plural(n_edits, "deterministic edit"),
            _plural(sum(len(v) for v in scrubbed.values()), "finalist"),
        ),
    )

    # -- score ------------------------------------------------------------
    # THE YARDSTICK RUNS HERE, AND ONLY HERE. Everything above this line was
    # scored by the guide, which is a search heuristic and is not reported as
    # a probability of anything.
    finalist_scores: Dict[int, List[Optional[float]]] = {}
    if yardstick is None:
        yield event(
            "score",
            "skip",
            1.0,
            "no yardstick detector available; finalists cannot be ranked by "
            "the reported score",
        )
        finalist_scores = {i: [None] * len(v) for i, v in scrubbed.items()}
    else:
        yield event(
            "score",
            "start",
            0.0,
            "scoring finalists with %s" % pipeline_mod._scorer_name(finalist_scorer),
        )
        for n, outcome in enumerate(outcomes):
            row = [_score_with(finalist_scorer, t) for t in scrubbed[outcome.index]]
            finalist_scores[outcome.index] = row
            yield event(
                "score",
                "progress",
                (n + 1) / max(1, len(outcomes)),
                "paragraph %d of %d: %s"
                % (
                    n + 1,
                    len(outcomes),
                    ", ".join(
                        "unscored" if p is None else "p(AI) %.3f" % p for p in row
                    )
                    or "no finalist",
                ),
            )
        yield event(
            "score",
            "done",
            1.0,
            "scored %d finalists with the yardstick"
            % sum(len(v) for v in finalist_scores.values()),
        )

    # -- verify -----------------------------------------------------------
    # `pipeline._gate_candidate`, imported not reimplemented.
    yield event("verify", "start", 0.0, "checking hard gates")
    survivors: Dict[int, List[Tuple[Optional[float], int, str]]] = {}
    all_gates: Dict[str, int] = {}
    for n, outcome in enumerate(outcomes):
        rows: List[Tuple[Optional[float], int, str]] = []
        failures: List[str] = []
        for j, candidate in enumerate(scrubbed[outcome.index]):
            gates = pipeline_mod._gate_candidate(outcome.original, candidate, cfg)
            for g in gates:
                all_gates[g] = all_gates.get(g, 0) + 1
            if gates:
                failures.extend(gates)
            else:
                rows.append((finalist_scores[outcome.index][j], j, candidate))
        survivors[outcome.index] = rows
        outcome.gates = sorted(set(failures))
        yield event(
            "verify",
            "progress",
            (n + 1) / max(1, len(outcomes)),
            "paragraph %d of %d: %d of %s passed every gate%s"
            % (
                n + 1,
                len(outcomes),
                len(rows),
                _plural(len(scrubbed[outcome.index]), "finalist"),
                "" if rows else " (%s)" % ", ".join(sorted(set(failures))),
            ),
        )
    yield event(
        "verify",
        "done",
        1.0,
        "%d of %s passed every gate"
        % (
            sum(len(v) for v in survivors.values()),
            _plural(sum(len(v) for v in scrubbed.values()), "finalist"),
        ),
    )

    # -- select -----------------------------------------------------------
    yield event("select", "start", 0.0, "ranking survivors by the yardstick")
    for n, outcome in enumerate(outcomes):
        rows = survivors[outcome.index]
        if not rows:
            outcome.fallback_reason = (
                "no finalist passed the gates (%s); kept the original"
                % (", ".join(outcome.gates) or "nothing was generated")
            )
            outcome.ai_probability_after = outcome.ai_probability_before
            outcome.guide_probability_after = outcome.guide_probability_before
            yield event(
                "select",
                "progress",
                (n + 1) / max(1, len(outcomes)),
                "paragraph %d of %d: every finalist rejected, keeping the original"
                % (n + 1, len(outcomes)),
            )
            continue
        scored_rows = [r for r in rows if r[0] is not None]
        if scored_rows:
            best = min(scored_rows, key=lambda r: (r[0], r[1]))
        else:
            best = min(rows, key=lambda r: r[1])
        outcome.chosen = best[2]
        outcome.ai_probability_after = best[0]
        outcome.guide_probability_after = _score_with(guide_obj, best[2])
        outcome.quality = _quality(outcome.original, best[2])
        yield event(
            "select",
            "progress",
            (n + 1) / max(1, len(outcomes)),
            "paragraph %d of %d: finalist %d wins (%s), %d survived"
            % (
                n + 1,
                len(outcomes),
                best[1] + 1,
                "unscored"
                if best[0] is None
                else "p(AI) %.3f by the yardstick" % best[0],
                len(rows),
            ),
        )
    yield event(
        "select",
        "done",
        1.0,
        "%d of %s rewritten"
        % (
            sum(1 for o in outcomes if o.changed),
            _plural(len(outcomes), "paragraph"),
        ),
    )

    # -- repair -----------------------------------------------------------
    # The stage exists in `pipeline.STAGES` so both pipelines feed one
    # checklist; the guided search's per-sentence fallback is its repair.
    yield event("repair", "skip", 1.0, "no repair stage in the guided search")

    # -- finalize ---------------------------------------------------------
    yield event("finalize", "start", 0.0, "reassembling and re-measuring")
    humanized = "\n\n".join(o.chosen.strip() for o in outcomes if o.chosen.strip())
    after = _measure(humanized, yardstick)
    p_after = after["ai_probability"]
    guide_after = _score_with(guide_obj, humanized)

    transfer = _transfer(
        [(o.guide_probability_after, o.ai_probability_after) for o in outcomes]
        + [(guide_after, p_after)]
    )
    summary = {
        "engine": "guided",
        "mode": cfg.mode,
        "model": cfg.resolved_model(),
        "backend": getattr(backend, "name", ""),
        "guide_model": cfg.guide_model if guide_obj is not None else None,
        "guide_engine": GUIDE_ENGINE if guide_obj is not None else None,
        "guide_available": guide_obj is not None,
        "guide_unavailable_reason": guide_reason,
        "yardstick_model": yardstick_name,
        "yardstick": yardstick.describe()
        if isinstance(yardstick, yardstick_mod.Yardstick)
        else None,
        "candidate_scorer": pipeline_mod._scorer_name(finalist_scorer)
        if finalist_scorer is not None
        else None,
        "objective": cfg.objective,
        "beam_width": cfg.beam_width,
        "n_samples": cfg.n_samples,
        "guide_context": cfg.guide_context,
        "n_edits": 0,
        "n_paragraphs": len(outcomes),
        "n_sentences": sum(o.n_sentences for o in outcomes),
        "n_fallback_sentences": sum(o.n_fallback_sentences for o in outcomes),
        "paragraphs_rewritten": sum(1 for o in outcomes if o.changed),
        "paragraphs_unchanged": sum(1 for o in outcomes if not o.changed),
        "gate_rejections": dict(sorted(all_gates.items())),
        "quality_flags": _flag_counts(outcomes),
        "content_overlap": round(content_overlap(original, humanized), 4),
        # Every number below is the yardstick's. See the module docstring.
        "risk_delta": None
        if (p_before is None or p_after is None)
        else round(p_after - p_before, 6),
        "label_before": before.get("label"),
        "label_after": after.get("label"),
        "verdict_flipped": bool(
            before.get("label") == "ai" and after.get("label") == "human"
        ),
        "guide_transfer": transfer,
        "seconds": round(clock(), 3),
        "generation_seconds": round(totals["generation_seconds"], 3),
        "generation_tokens": totals["generation_tokens"],
        "guide_calls": totals["guide_calls"],
        "guide_seconds": round(totals["guide_seconds"], 3),
        "tokens_per_second": round(
            totals["generation_tokens"] / totals["generation_seconds"], 1
        )
        if totals["generation_seconds"] > 0.05
        else None,
        "batched": batched,
    }
    guide_block = {
        "model": cfg.guide_model if guide_obj is not None else None,
        "engine": GUIDE_ENGINE if guide_obj is not None else None,
        "available": guide_obj is not None,
        "reason": guide_reason,
        "probability_before": guide_before,
        "probability_after": guide_after,
        "delta": None
        if (guide_before is None or guide_after is None)
        else round(guide_after - guide_before, 6),
        "calls": totals["guide_calls"],
        "seconds": round(totals["guide_seconds"], 3),
        "note": (
            "This is the in-loop search heuristic, not a verdict. It called 8 "
            "of 14 genuine human PMC paragraphs AI on this repo's own bench. "
            "The reported probability is `after.ai_probability`, from %s."
            % YARDSTICK_MODEL
        ),
    }
    result = GuidedResult(
        original=original,
        humanized=humanized,
        model=cfg.resolved_model(),
        backend=getattr(backend, "name", ""),
        before=before,
        after=after,
        guide=guide_block,
        summary=summary,
        paragraphs=outcomes,
        stages=stage_timings,
    )
    detail = "%s in %.1fs" % (
        "verdict flipped ai -> human"
        if summary["verdict_flipped"]
        else "verdict unchanged (%s)" % (after.get("label") or "unscored"),
        summary["seconds"],
    )
    now = clock()
    stage_timings.append(
        {
            "stage": "finalize",
            "status": "done",
            "seconds": round(now - stage_started.pop("finalize", now), 3),
            "detail": detail,
            "round": 1,
        }
    )
    yield ProgressEvent(
        stage="finalize",
        status="done",
        progress=1.0,
        detail=detail,
        elapsed=now,
        round=1,
        result=result.as_dict(),
        result_object=result,
    )


def _flag_counts(outcomes: Sequence[GuidedParagraph]) -> Dict[str, int]:
    """How many chosen paragraphs carried each advisory quality flag."""
    counts: Dict[str, int] = {}
    for outcome in outcomes:
        for flag in outcome.quality.get("flags", ()):
            counts[flag] = counts.get(flag, 0) + 1
    return dict(sorted(counts.items()))


def humanize_guided(
    text: str,
    config: Optional[GuidedConfig] = None,
    backend: Optional[llm_mod.Backend] = None,
    detector: Any = None,
    guide: Any = None,
    on_event: Optional[Callable[[ProgressEvent], None]] = None,
) -> GuidedResult:
    """Blocking wrapper over `stream()`. Same arguments, same guarantees."""
    final: Optional[GuidedResult] = None
    for ev in stream(
        text, config=config, backend=backend, detector=detector, guide=guide
    ):
        if on_event is not None:
            on_event(ev)
        if ev.result_object is not None:
            final = ev.result_object
    if final is None:  # pragma: no cover - stream always ends with finalize
        raise RuntimeError("guided decoding produced no result")
    return final
