"""The LLM humanizing pipeline: generate, scrub, score, gate, select.

This is the orchestrator. `llm.py` knows how to turn a paragraph into prompts;
`transforms.py` and `engine.py` know how to make deterministic edits and how to
check that an edit did not change a fact; `detectors.local.ModernDetector`
knows how to score. This module is the only thing that knows the *order*, and
the order is the design.

The order, and why each step is where it is
-------------------------------------------
::

    analyze -> plan -> generate -> scrub -> score -> verify -> select -> finalize

**Segment first.** Paragraph by paragraph, so a long document stays inside the
time budget, each rewrite is independently verifiable against its own source,
and a paragraph whose candidates all fail can fall back to its original without
poisoning the rest of the document.

**Generate N diverse candidates.** research/08: correlated candidates make
best-of-N decay as a power law rather than exponentially, so the diversity has
to be engineered. It comes from a different persona and a different structural
instruction per candidate (`llm.CANDIDATE_SPECS`), with temperature varying
underneath. Temperature alone was measured here to buy almost nothing.

**Scrub after the model, never before.** The measured reason: asked to
humanize, Qwen2.5-3B-Instruct returns text still containing "rapidly evolving
digital landscape", "pivotal", "multifaceted", "robust" and "Consequently". The
fingerprint comes from instruction tuning (research/04), so the model
*reintroduces* exactly the vocabulary the deterministic pass removes. Scrubbing
the input and then generating would throw the work away. `_scrub()` runs the
same three transform passes `engine.humanize` runs, under the same meaning
gate, on the model's output.

**Score, then gate, then rank.** Gates are hard rejections, not soft weights
(research/00 §6, research/05 §6). A candidate that mangles a number is not a
slightly worse candidate, it is not a candidate. The gates are:

* every number, date, quotation, citation and named entity preserved exactly
  (`engine.invariants`, reused rather than reimplemented -- see
  `_invariant_failures` for the one deliberate difference);
* length ratio within ±25% of the source paragraph;
* no candidate shorter than 70% of the source;
* content-word overlap with the source at or above `min_content_overlap`.

That last one is not in the brief's list and it is the one that does the most
work. Without it the pipeline reports a triumphant score drop for text that has
quietly changed subject - see "What this actually achieves" below.

**Select the best surviving candidate**, or fall back to the paragraph's
original text when none survives. Falling back is reported, never hidden:
`summary["paragraphs_unchanged"]` and each paragraph's `fallback_reason` say so.

What this actually achieves, measured
-------------------------------------
Measured on an M4 Pro against `desklib/ai-text-detector-v1.01`, over 9 AI
paragraphs (3 hand-written in the stereotypical register, 6 generated by
Qwen2.5-3B-Instruct) and 5 human PMC paragraphs, at 6 candidates per paragraph:

===========================  ==========  ===========  =============
metric                       source      LLM path     rule-based
===========================  ==========  ===========  =============
verdict flips (ai -> human)  --          **0 of 9**   **0 of 9**
mean p(AI)                   1.0000      0.9998       1.0000
mean AI vocabulary per 1k    31.3        13.7         14.9
mean sentence-length CV      0.232       0.304        0.219
in the 0.42-0.60 CV band     0 of 9      0 of 9       0 of 9
mean wall clock              --          12.4 s       < 0.1 s
===========================  ==========  ===========  =============

**It does not flip the verdict, and neither does the rule-based engine.** Say
that plainly rather than quoting the probability drop, which is 0.0001 and
means nothing. research/13's DUPE result is the same shape: attacks that halved
false-negative rates still produced 1 "Human" verdict in 400.

The reason is not a tuning failure, it is a measurement. Three things were
tried and all three landed in the same place:

1. Sampling. Six completions of one prompt at temperatures from 0.7 to 2.0,
   with `top_p` and `min_p` variants: every one scored 1.0000.
2. Prompting. Personas, structural constraints, a banned-vocabulary list, a
   human style exemplar and a hard style contract: faithful candidates score
   0.9996-1.0000.
3. The base checkpoint (`style="freeform"`), which research/05 §6 predicts
   should not carry the instruction-tuning fingerprint. It does produce
   candidates scoring 0.02-0.43 - and every one of them has a content-word
   overlap with the source of 0.01 to 0.15. They are fluent text about a
   different subject. Across the same 14 samples, 3 of 84 freeform candidates
   passed the gates and none of the three lowered the score.

The controlling measurement is simpler than any of those: asked to paraphrase
genuine human PMC paragraphs scoring 0.02-0.24, this model returns text scoring
0.73-1.00. Passing text through a 3B instruct model *makes it look generated*,
whatever the prompt says. Best-of-N cannot select its way out of that, because
the property is in every candidate.

So the honest summary is: **at 3B, on this detector, evasion is available only
in exchange for meaning, and this pipeline is configured to refuse that trade.**
What it does deliver, with meaning gated, is the stylometric half of research/00
§4 - AI vocabulary per 1,000 words from 31.3 to 13.7, sentence-length CV from
0.232 toward the band - and both numbers are in the response next to the
verdict, so nobody has to take the flattering one on faith.

The human-text safety check passed: over 5 genuine PMC paragraphs none crossed
to "ai", the largest movement was -0.0438 (an improvement), and 4 of the 5 were
returned untouched because every candidate failed a gate.

2026-09-07: the priority order was reversed, and the yardstick changed
------------------------------------------------------------------------
Everything above was measured with meaning gated first and desklib as the
judge. The product goal is the other way round: **pass the detector first,
then slowly improve the writing**, and the detector to pass is GPTZero. Three
things changed, all of them configuration rather than new machinery:

1. **The yardstick is `detectors.yardstick`.** GPTZero when `GPTZERO_API_KEY`
   is set, otherwise a named local proxy that the response labels as such.
   Candidates are ranked by the free local proxy; only the document's
   before/after verdict is bought from GPTZero (research/07 §7: validator,
   not inner-loop reward). `summary["yardstick"]` says which one produced the
   number you are reading.
2. **`PipelineConfig.objective` defaults to `"evade"`.** The factual
   invariants stay hard. The three stylistic gates widen (`GATE_PRESETS`),
   selection is a pure argmin over the proxy score, and `quality_weight` is
   the knob that reintroduces the writing bands a little at a time.
3. **`style` defaults to `"mixed"`.** Half the candidates come from the base
   checkpoint, which research/13 §2 puts at 96-99% human on GPTZero for the
   same model family, and which was previously losing only on the content
   gate that `evade` relaxes. The style contract and `llm.CANDIDATE_SPECS`
   gained sentence-structure rules (openers, length runs, tricolons) taken
   from GPTZero's own published cadence heuristics (research/06 §1, §6).

The measured table above is now the *baseline* the `evade` objective is
benchmarked against (`scripts/bench_evasion.py`), not a description of the
current default.

Progress events
---------------
`stream()` is a generator of `ProgressEvent`. Stage names are stable and are
the frontend's checkbox list::

    analyze plan generate scrub score verify select finalize

`status` is one of `start`, `progress`, `done`, `skip`. `progress` is 0.0-1.0
and is non-decreasing within a stage occurrence. `detail` is written to be
shown to a person: "candidate 3 of 6, paragraph 2 of 4". When a refinement
round runs, the stages repeat with `round` incremented; within each occurrence
progress still runs 0 to 1.

The final event is always `finalize/done` and it alone carries `result`, the
full payload.
"""

from __future__ import annotations

import math
import re
import time
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, Iterator, List, Optional, Sequence, Tuple

from ..detectors import yardstick as yardstick_mod
from ..features import extract_from_document
from ..text import Document, normalize, split_paragraphs, words
from . import llm as llm_mod
from .engine import invariants
# `_gate` and `_resolve_overlaps` are engine internals. They are imported
# rather than reimplemented because a second copy of the overlap rule and the
# per-edit meaning gate is exactly how two code paths start disagreeing about
# what a safe edit is. The alternative - calling `engine.humanize()` - is not
# usable here: it scores the text with the DeBERTa detector twice per call, and
# this pipeline scrubs up to fifty candidates per document.
from .engine import _gate as _gate_edits
from .engine import _resolve_overlaps
from .transforms import PASSES, Edit, apply_edits, config_for

__all__ = [
    "STAGES",
    "ProgressEvent",
    "Candidate",
    "ParagraphOutcome",
    "LlmHumanizeResult",
    "PipelineConfig",
    "stream",
    "humanize_llm",
    "pipeline_available",
    "pipeline_unavailable_reason",
]


#: The UI's checkbox list. Stable; the frontend keys off these strings.
STAGES: Tuple[str, ...] = (
    "analyze",
    "plan",
    "generate",
    "scrub",
    "score",
    "verify",
    "select",
    "finalize",
)

#: Verdict threshold. `DetectorResult.label` already applies it, but the
#: pipeline needs it for the refinement decision too, so it is named once.
AI_THRESHOLD = 0.5

#: Sentence-length CV band for human prose (research/10, via features.shape).
HUMAN_SENTENCE_CV = (0.42, 0.60)


# ------------------------------------------------------------------- events


@dataclass
class ProgressEvent:
    """One line of the progress stream.

    The five keys `stage`, `status`, `progress`, `detail`, `elapsed` are the
    contract. `round` is additive and safe to ignore. `result` is present on
    exactly one event - `finalize/done` - and is dropped from `as_dict()`
    everywhere else, so a client can render every event the same way and only
    special-case the last.
    """

    stage: str
    status: str
    progress: float
    detail: str
    elapsed: float
    round: int = 1
    result: Optional[Dict[str, Any]] = None
    #: The same result as a dataclass, for in-process callers. Never
    #: serialised: `as_dict()` is the wire format and it carries `result`.
    result_object: Optional[Any] = None

    def as_dict(self) -> Dict[str, Any]:
        payload: Dict[str, Any] = {
            "stage": self.stage,
            "status": self.status,
            "progress": round(float(self.progress), 4),
            "detail": self.detail,
            "elapsed": round(float(self.elapsed), 3),
            "round": self.round,
        }
        if self.result is not None:
            payload["result"] = self.result
        return payload


class _Clock:
    """Monotonic elapsed seconds since the run started."""

    def __init__(self) -> None:
        self.t0 = time.perf_counter()

    def __call__(self) -> float:
        return time.perf_counter() - self.t0


# --------------------------------------------------------------- quality


_SYLLABLE_RE = re.compile(r"[aeiouy]+", re.IGNORECASE)

#: Function words dropped before measuring content overlap. Overlap on "the"
#: and "of" measures nothing; overlap on the nouns and verbs is the point.
_STOPWORDS = frozenset(
    """
    a an and are as at be been being but by can could did do does for from had
    has have he her him his how i if in into is it its may me might most much
    must my no nor not of on or our out over she should so some such than that
    the their them then there these they this those to too under up us was we
    were what when where which while who whom whose why will with would you
    your it's don't
    """.split()
)


def _content_words(text: str) -> "frozenset":
    return frozenset(
        w.lower()
        for w in words(text)
        if len(w) > 2 and w.lower() not in _STOPWORDS
    )


def content_overlap(source: str, candidate: str) -> float:
    """Share of the source's content words that survive into the candidate.

    A blunt proxy for "did this rewrite stay on topic", and deliberately
    asymmetric: it penalises *dropping* the source's content, not adding to it,
    because a rewrite that loses half the source's nouns has lost half the
    document whatever else it did. It is not entailment and it is not a
    semantic similarity model - see `engine`'s docstring on the same point.
    Measured here it separates the two failure modes cleanly: faithful
    candidates land at 0.65-1.00, off-topic ones at 0.01-0.15.
    """
    src = _content_words(source)
    if not src:
        return 1.0
    return len(src & _content_words(candidate)) / len(src)


def _syllables(word: str) -> int:
    """Crude English syllable count: vowel runs, minus a silent final `e`."""
    groups = _SYLLABLE_RE.findall(word)
    n = len(groups)
    if word.lower().endswith("e") and n > 1 and not word.lower().endswith(("le", "ee")):
        n -= 1
    return max(1, n)


def flesch_reading_ease(text: str) -> float:
    """Flesch reading ease, approximately.

    The syllable counter is a vowel-run heuristic, so this is accurate to a few
    points, not exactly. It is used as a **sanity check, not a gate**: the
    question it answers is "did the rewrite quietly turn academic prose into
    listicle prose, or the reverse", and a few points either way does not
    change that answer. Academic prose typically lands 10-40; a large move in
    either direction is worth a flag.
    """
    doc = Document.parse(text)
    sentences = [s for s in doc.sentences if s.words]
    tokens = words(text)
    if not sentences or not tokens:
        return float("nan")
    syllables = sum(_syllables(w) for w in tokens)
    return (
        206.835
        - 1.015 * (len(tokens) / len(sentences))
        - 84.6 * (syllables / len(tokens))
    )


def _quality(source: str, candidate: str) -> Dict[str, Any]:
    """Readability, shape and vocabulary numbers for one candidate."""
    feats = extract_from_document(Document.parse(candidate))
    cv = feats.get("sent_len_cv", float("nan"))
    ease = flesch_reading_ease(candidate)
    source_ease = flesch_reading_ease(source)
    flags: List[str] = []
    if isinstance(cv, float) and math.isfinite(cv) and not (
        HUMAN_SENTENCE_CV[0] <= cv <= HUMAN_SENTENCE_CV[1]
    ):
        flags.append("sent_len_cv_outside_human_band")
    if math.isfinite(ease) and math.isfinite(source_ease) and abs(ease - source_ease) > 20:
        flags.append("readability_shifted")
    overlap = content_overlap(source, candidate)
    if overlap < 0.55:
        # Not a gate at this threshold, a warning: 0.55 is where a rewrite has
        # started paraphrasing nouns away rather than merely restructuring.
        flags.append("possible_semantic_drift")
    return {
        "content_overlap": round(overlap, 4),
        "sent_len_cv": None if not math.isfinite(cv) else round(cv, 4),
        "sent_len_mean": round(feats.get("sent_len_mean", float("nan")), 3)
        if math.isfinite(feats.get("sent_len_mean", float("nan")))
        else None,
        "ai_vocab_hits_per_1k": round(feats.get("ai_vocab_hits_per_1k", 0.0), 3),
        "flesch_reading_ease": None if not math.isfinite(ease) else round(ease, 1),
        "flags": flags,
    }


# ----------------------------------------------------------------- scrubbing


def _scrub(text: str, aggressiveness: str = "strong") -> Tuple[str, List[Edit]]:
    """Run the deterministic transform passes over model output.

    Identical in behaviour to the loop inside `engine.humanize`, minus the two
    detector calls that function makes - which is the entire reason this exists
    separately. Returns `(text, accepted_edits)`; the edits are reported so the
    response can show what the scrub did to the winning candidate.
    """
    cfg = config_for(aggressiveness)
    working = normalize(text or "")
    accepted_all: List[Edit] = []
    for stage in PASSES:
        active = [(name, fn) for name, fn in stage if name in cfg.transforms]
        if not active:
            continue
        stage_doc = Document.parse(working)
        ranked: List[Tuple[int, Edit]] = []
        for rank, (_name, transform) in enumerate(active):
            for edit in transform(stage_doc, cfg):
                ranked.append((rank, edit))
        accepted, _dropped = _gate_edits(stage_doc.text, _resolve_overlaps(ranked))
        working = apply_edits(stage_doc.text, accepted)
        accepted_all.extend(accepted)
    return working, accepted_all


# --------------------------------------------------------------- the records


@dataclass
class Candidate:
    """One rewrite of one paragraph, with everything measured about it."""

    paragraph_index: int
    index: int
    persona: str
    constraint: str
    temperature: float
    round: int = 1
    raw: str = ""
    scrubbed: str = ""
    scrub_edits: List[Edit] = field(default_factory=list)
    #: The *candidate scorer's* number (the local proxy), not the yardstick's.
    #: Kept under this name for the frontend; `as_dict` also emits it as
    #: `proxy_probability` so the distinction is visible on the wire.
    ai_probability: Optional[float] = None
    gates: List[str] = field(default_factory=list)
    quality: Dict[str, Any] = field(default_factory=dict)
    style: str = "faithful"

    @property
    def passed(self) -> bool:
        return not self.gates

    def as_dict(self, with_text: bool = True) -> Dict[str, Any]:
        payload: Dict[str, Any] = {
            "paragraph_index": self.paragraph_index,
            "index": self.index,
            "persona": self.persona,
            "constraint": self.constraint,
            "temperature": self.temperature,
            "style": self.style,
            "round": self.round,
            "ai_probability": self.ai_probability,
            "proxy_probability": self.ai_probability,
            "gates": list(self.gates),
            "passed": self.passed,
            "quality": self.quality,
            "n_scrub_edits": len(self.scrub_edits),
        }
        if with_text:
            payload["text"] = self.scrubbed
        return payload


@dataclass
class ParagraphOutcome:
    """What happened to one paragraph."""

    index: int
    original: str
    chosen: str
    chosen_index: Optional[int] = None
    ai_probability_before: Optional[float] = None
    ai_probability_after: Optional[float] = None
    candidates: List[Candidate] = field(default_factory=list)
    fallback_reason: Optional[str] = None

    @property
    def changed(self) -> bool:
        return self.chosen.strip() != self.original.strip()

    def as_dict(self) -> Dict[str, Any]:
        return {
            "index": self.index,
            "original": self.original,
            "humanized": self.chosen,
            "winning_candidate": self.chosen_index,
            "ai_probability_before": self.ai_probability_before,
            "ai_probability_after": self.ai_probability_after,
            "changed": self.changed,
            "fallback_reason": self.fallback_reason,
            "candidates": [c.as_dict() for c in self.candidates],
        }


@dataclass
class LlmHumanizeResult:
    """The full result. `as_dict()` is the HTTP response body."""

    original: str
    humanized: str
    model: str
    backend: str = ""
    before: Dict[str, Any] = field(default_factory=dict)
    after: Dict[str, Any] = field(default_factory=dict)
    summary: Dict[str, Any] = field(default_factory=dict)
    paragraphs: List[ParagraphOutcome] = field(default_factory=list)
    stages: List[Dict[str, Any]] = field(default_factory=list)
    edits: List[Edit] = field(default_factory=list)

    @property
    def changed(self) -> bool:
        return self.humanized != self.original

    def as_dict(self) -> Dict[str, Any]:
        """The POST /api/humanize/llm body.

        A superset of `HumanizeResult.as_dict()` - `original`, `humanized`,
        `edits`, `before`, `after`, `summary` mean exactly what they mean on
        `POST /api/humanize` - plus `model`, `stages` and `paragraphs`.

        `edits` is the deterministic scrub applied to the **winning
        candidates**, not a diff between the original and the output. The LLM
        rewrite is not expressible as a span edit list, so there is nothing
        honest to put there for it; `paragraphs[i].original` and
        `paragraphs[i].humanized` are the before/after a caller should diff.
        """
        return {
            "original": self.original,
            "humanized": self.humanized,
            "edits": [e.as_dict() for e in self.edits],
            "before": self.before,
            "after": self.after,
            "summary": self.summary,
            "model": self.model,
            "backend": self.backend,
            "stages": list(self.stages),
            "paragraphs": [p.as_dict() for p in self.paragraphs],
        }


OBJECTIVE_EVADE = "evade"
OBJECTIVE_FAITHFUL = "faithful"

#: The stylistic gates per objective. The factual invariants are not here
#: because they are not adjustable: a rewrite that changes a number is wrong
#: under every objective.
#:
#: `evade` widens content overlap to 0.30 because the measured off-topic
#: failure sits at 0.01-0.15 and faithful restructurings at 0.65-1.00, so
#: 0.30 still separates them; it widens length to -40%/+40% because
#: research/06 §3 (Perkins) puts paragraph-length variation inside the one
#: structural lever with a peer-reviewed effect on GPTZero.
GATE_PRESETS: Dict[str, Dict[str, float]] = {
    OBJECTIVE_EVADE: {
        "min_content_overlap": 0.30,
        "max_length_ratio_delta": 0.40,
        "min_length_ratio": 0.60,
    },
    OBJECTIVE_FAITHFUL: {
        "min_content_overlap": 0.45,
        "max_length_ratio_delta": 0.25,
        "min_length_ratio": 0.70,
    },
}


@dataclass
class PipelineConfig:
    """Everything tunable about one run.

    `time_budget_s` is a soft budget: it is checked between paragraphs and
    between rounds, never mid-generation, so one paragraph can overshoot it.
    30 seconds is the user-accepted figure and is roughly 1800 generated tokens
    at the measured single-stream rate, or six paragraphs x six candidates at
    the measured batched rate.
    """

    n_candidates: int = 6
    #: `faithful` (instruct checkpoint only), `freeform` (base checkpoint
    #: only) or `mixed` (alternate the two). `mixed` is the default under the
    #: `evade` objective because research/13 §2 puts base-model text at
    #: 96-99% human on GPTZero against 17-30% for the same model instruction
    #: tuned, and the base candidates were only ever losing here on the
    #: content gate, which `evade` relaxes.
    style: str = "mixed"
    aggressiveness: str = "strong"
    time_budget_s: float = 30.0
    #: Round 2 re-runs only the paragraphs the proxy still calls AI.
    rounds: int = 2
    #: **The priority order.** `evade` (default since 2026-09-07): the
    #: detector score is the objective, the factual invariants (numbers,
    #: dates, quotations, citations, names) stay hard, and the three
    #: stylistic gates are widened to the values below. `faithful`: the
    #: original tight gates, for callers who want the old behaviour.
    objective: str = OBJECTIVE_EVADE
    #: How much a candidate's distance from the human-quality bands counts
    #: against it at selection, in units of AI probability. 0.0 ranks on the
    #: score alone; the "slowly improve the writing" knob is to raise this.
    quality_weight: float = 0.0
    #: Reject a candidate that keeps less than this share of the source's
    #: content words. See `content_overlap`. `None` means "the objective's
    #: default".
    min_content_overlap: Optional[float] = None
    #: |len(candidate)/len(source) - 1| may not exceed this.
    max_length_ratio_delta: Optional[float] = None
    #: Independent floor, stated separately because it is the failure that
    #: matters most: a candidate that silently drops half the paragraph.
    min_length_ratio: Optional[float] = None
    model: Optional[str] = None

    def __post_init__(self) -> None:
        if self.objective not in GATE_PRESETS:
            raise ValueError(
                "objective must be one of %s" % ", ".join(sorted(GATE_PRESETS))
            )
        if self.style not in ("faithful", "freeform", "mixed"):
            raise ValueError("style must be faithful, freeform or mixed")
        preset = GATE_PRESETS[self.objective]
        if self.min_content_overlap is None:
            self.min_content_overlap = preset["min_content_overlap"]
        if self.max_length_ratio_delta is None:
            self.max_length_ratio_delta = preset["max_length_ratio_delta"]
        if self.min_length_ratio is None:
            self.min_length_ratio = preset["min_length_ratio"]

    def styles(self) -> Tuple[str, ...]:
        return ("faithful", "freeform") if self.style == "mixed" else (self.style,)

    def model_for(self, style: str) -> str:
        """The checkpoint one style generates with.

        `model` overrides the instruct checkpoint only: a base checkpoint is
        a different object and there is no sensible single override for both.
        """
        if style == "freeform":
            return llm_mod.FREEFORM_MODEL
        return self.model or llm_mod.DEFAULT_MODEL

    def resolved_model(self) -> str:
        return " + ".join(self.model_for(s) for s in self.styles())


# ------------------------------------------------------------ the detector


def _detector() -> Any:
    """The in-loop candidate scorer: `detectors.yardstick.proxy()`'s model.

    Local, free, a published checkpoint. It is *not* necessarily the yardstick:
    when `GPTZERO_API_KEY` is set the yardstick is GPTZero and this is the
    desklib stand-in that ranks fifty candidates without spending money on
    them. `yardstick.proxy()` returns the yardstick's own object when the two
    coincide, so nothing is loaded twice.
    """
    return yardstick_mod.proxy().detector


def _yardstick() -> Any:
    """The document-level verdict: `detectors.yardstick.resolve()`."""
    return yardstick_mod.resolve()


def _score(text: str, detector: Any) -> Optional[float]:
    """AI probability for one string, or None when the model cannot run."""
    if detector is None or not text or not text.strip():
        return None
    try:
        if hasattr(detector, "available") and not detector.available():
            return None
        value = float(detector.score(text).ai_probability)
    except Exception:  # noqa: BLE001 - a missing model must not fail a rewrite
        return None
    return None if value != value else value


def _score_and_label(text: str, detector: Any) -> Tuple[Optional[float], Optional[str]]:
    """Probability plus the detector's *own* label when it gives one.

    GPTZero returns a three-way verdict ({human, ai, mixed}) that is not a
    threshold on its probability (research/07 §2: the class is the argmax of
    a remapped document head). Reading the label off the result rather than
    re-deriving it from 0.5 is what makes `verdict_flipped` mean "GPTZero
    said human" when GPTZero is the yardstick. Detectors without a label fall
    back to the threshold.
    """
    if detector is None or not text or not text.strip():
        return None, None
    try:
        if hasattr(detector, "available") and not detector.available():
            return None, None
        result = detector.score(text)
    except Exception:  # noqa: BLE001
        return None, None
    try:
        probability: Optional[float] = float(result.ai_probability)
    except (TypeError, ValueError):
        probability = None
    if probability is not None and probability != probability:
        probability = None
    label = getattr(result, "label", None)
    if label not in ("human", "ai", "mixed"):
        label = _label(probability)
    return probability, label


def _label(probability: Optional[float]) -> Optional[str]:
    if probability is None:
        return None
    return "ai" if probability >= AI_THRESHOLD else "human"


# ------------------------------------------------------------- availability


def pipeline_available(config: Optional[PipelineConfig] = None) -> bool:
    """Whether the LLM path can run at all right now."""
    return llm_mod.mlx_available()


def pipeline_unavailable_reason(
    config: Optional[PipelineConfig] = None,
) -> Optional[str]:
    """A user-facing sentence, naming the rule-based fallback."""
    return llm_mod.mlx_unavailable_reason()


# ------------------------------------------------------------- the pipeline


def _invariant_failures(source: str, candidate: str) -> List[str]:
    """The meaning invariants, adapted from span edits to whole rewrites.

    `engine.invariants` is reused unchanged for numbers, quotations,
    citations and dates: those are evidence, they are compared as exact
    multisets, and a whole-paragraph rewrite has no more licence to alter one
    than a span edit does.

    **Entities are the one deliberate difference, and it is a correctness fix
    rather than a relaxation.** `engine.invariants` compares the capitalised
    mid-sentence runs of the two texts as *sets*, and `engine._entities` drops
    each sentence's first token because sentence-initial capitalisation is
    orthography, not identity. That is exactly right for a span edit, which
    moves at most one sentence boundary. It is wrong for a rewrite that
    reorders sentences: a name that sat mid-sentence in the source and opens a
    sentence in the candidate is dropped from the candidate's set and the
    source's set keeps it, so a perfectly faithful rewrite reports a corrupted
    entity. Measured on the benchmark corpus this fired on 48 of 84 candidates,
    almost all of them faithful.

    So the entity test here is directional and positional-agnostic: every
    capitalised run the source contains must still appear, verbatim and
    case-sensitively, somewhere in the candidate. That still catches the
    failure the gate exists for - a name vanishing, or being respelled - and it
    stops flagging sentence order as a factual change. It does not object to a
    *new* capitalised run, which a reordering rewrite legitimately produces.
    """
    before, after = invariants(source), invariants(candidate)
    failures = [
        key
        for key in ("numbers", "quotations", "citations", "dates")
        if before[key] != after[key]
    ]
    if any(entity not in candidate for entity in before["entities"]):
        failures.append("entities")
    return failures


def _gate_candidate(
    source: str,
    candidate: str,
    config: PipelineConfig,
) -> List[str]:
    """Names of every gate the candidate fails. Empty means it is usable.

    Every gate is a hard reject. There is no weighting and no score here on
    purpose (research/00 §6): a candidate that changed a number is not a
    slightly worse candidate.
    """
    failures: List[str] = []
    text = (candidate or "").strip()
    if not text:
        return ["empty"]

    n_source = len(words(source))
    n_candidate = len(words(text))
    if n_source == 0:
        return ["empty_source"]

    ratio = n_candidate / n_source
    if abs(ratio - 1.0) > config.max_length_ratio_delta:
        failures.append("length_ratio")
    if ratio < config.min_length_ratio:
        failures.append("too_short")
    if content_overlap(source, text) < config.min_content_overlap:
        failures.append("content_drift")
    for name in _invariant_failures(source, text):
        failures.append("invariant:" + name)
    if text == source.strip():
        failures.append("unchanged")
    return failures


def _plural(n: int, word: str) -> str:
    """`3 paragraphs` / `1 paragraph`. `detail` is rendered verbatim in the UI."""
    return "%d %s%s" % (n, word, "" if n == 1 else "s")


def _paragraph_segments(text: str) -> List[str]:
    """Paragraphs, or the whole document as one when it has no blank lines."""
    parts = split_paragraphs(text)
    return parts or ([text.strip()] if text.strip() else [])


def _measure(text: str, detector: Any) -> Dict[str, Any]:
    """The `before`/`after` block: feature vector plus the yardstick's verdict.

    `detector` is the yardstick, never the proxy. When it is a
    `detectors.yardstick.Yardstick` the block also names it, so a reader of
    the response can see whether `ai_probability` is a GPTZero number or a
    local stand-in.
    """
    doc = Document.parse(text)
    probability, label = _score_and_label(text, detector)
    block: Dict[str, Any] = {
        "ai_probability": probability,
        "label": label,
        "features": extract_from_document(doc),
    }
    if isinstance(detector, yardstick_mod.Yardstick):
        block["yardstick"] = {
            "name": detector.name,
            "kind": detector.kind,
            "model": detector.model,
        }
    return block


def stream(
    text: str,
    config: Optional[PipelineConfig] = None,
    backend: Optional[llm_mod.Backend] = None,
    detector: Any = None,
) -> Iterator[ProgressEvent]:
    """Run the pipeline, yielding a `ProgressEvent` for every step.

    Args:
        text: the document. Normalised on entry.
        config: see `PipelineConfig`. `None` uses the defaults.
        backend: an `llm.Backend`, used for every style. `None` builds one
            `MlxBackend` per style in `config.styles()`. Tests pass
            `llm.EchoBackend`.
        detector: anything with `.score(text).ai_probability`, used as both
            the yardstick and the candidate scorer. `None` uses
            `detectors.yardstick`: GPTZero for the document verdict when a
            key is configured, the local proxy for candidates. Pass `False`
            to score nothing, which makes every probability null and turns
            selection into "first candidate that passes the gates".

    Yields:
        `ProgressEvent`s in stage order. The final one is `finalize/done` and
        carries `result`.

    Raises:
        ValueError: on empty input.
        RuntimeError: when the backend cannot load. The message names the
            rule-based engine as the fallback.
    """
    if not text or not text.strip():
        raise ValueError("text must not be empty")

    cfg = config or PipelineConfig()
    if cfg.n_candidates <= 0:
        raise ValueError("n_candidates must be positive")
    clock = _Clock()
    stage_timings: List[Dict[str, Any]] = []
    stage_started: Dict[str, float] = {}

    # `det` ranks candidates; `yard` gives the document its verdict. They are
    # the same object unless the yardstick is GPTZero, in which case `det` is
    # the free local proxy -- see `detectors.yardstick` for why.
    yard: Any
    if detector is False:
        det = None
        yard = None
    elif detector is None:
        det = _detector()
        yard = _yardstick()
    else:
        det = detector
        yard = detector

    backends: Dict[str, llm_mod.Backend]
    if backend is None:
        backends = {
            s: llm_mod.default_backend(s, cfg.model_for(s)) for s in cfg.styles()
        }
    else:
        backends = {s: backend for s in cfg.styles()}
    backend = backends[cfg.styles()[0]]

    def event(
        stage: str,
        status: str,
        progress: float,
        detail: str,
        rnd: int = 1,
        result: Optional[Dict[str, Any]] = None,
    ) -> ProgressEvent:
        now = clock()
        if status == "start":
            stage_started[stage] = now
        if status in ("done", "skip"):
            started = stage_started.pop(stage, now)
            stage_timings.append(
                {
                    "stage": stage,
                    "status": status,
                    "seconds": round(now - started, 3),
                    "detail": detail,
                    "round": rnd,
                }
            )
        return ProgressEvent(stage, status, progress, detail, now, rnd, result)

    # -- analyze ----------------------------------------------------------
    yield event("analyze", "start", 0.0, "reading the document")
    original = normalize(text)
    segments = _paragraph_segments(original)
    doc = Document.parse(original)
    yield event(
        "analyze",
        "progress",
        0.4,
        "%s, %s, %s"
        % (
            _plural(len(segments), "paragraph"),
            _plural(doc.n_sentences, "sentence"),
            _plural(doc.n_words, "word"),
        ),
    )
    before = _measure(original, yard)
    p_before = before["ai_probability"]
    yield event(
        "analyze",
        "done",
        1.0,
        "scored the original with %s: %s"
        % (
            _scorer_name(yard),
            "detector unavailable"
            if p_before is None
            else "p(AI) %.3f, labelled %s" % (p_before, before["label"]),
        ),
    )

    # -- plan -------------------------------------------------------------
    yield event("plan", "start", 0.0, "choosing candidates")
    specs = llm_mod.specs_for(cfg.n_candidates, cfg.style)
    total_candidates = len(specs) * len(segments)
    est_tokens = sum(llm_mod.estimate_max_tokens(s) for s in segments) * len(specs)
    yield event(
        "plan",
        "done",
        1.0,
        "%s x %s = %s, up to ~%d generated tokens, budget %.0fs"
        % (
            _plural(len(specs), "candidate"),
            _plural(len(segments), "paragraph"),
            _plural(total_candidates, "rewrite"),
            est_tokens,
            cfg.time_budget_s,
        ),
    )

    outcomes = [
        ParagraphOutcome(index=i, original=s, chosen=s) for i, s in enumerate(segments)
    ]
    for outcome in outcomes:
        outcome.ai_probability_before = _score(outcome.original, det)

    generation_seconds = 0.0
    generation_tokens = 0
    used_batching = False
    backend_error: Optional[str] = None

    for rnd in range(1, max(1, cfg.rounds) + 1):
        targets = [
            o
            for o in outcomes
            if rnd == 1
            or (
                o.ai_probability_after is not None
                and o.ai_probability_after >= AI_THRESHOLD
            )
        ]
        if rnd > 1:
            if not targets:
                yield event(
                    "generate",
                    "skip",
                    1.0,
                    "round %d not needed: every paragraph is already below the "
                    "0.5 threshold" % rnd,
                    rnd,
                )
                break
            if clock() > cfg.time_budget_s:
                yield event(
                    "generate",
                    "skip",
                    1.0,
                    "round %d skipped: %.1fs budget already spent"
                    % (rnd, cfg.time_budget_s),
                    rnd,
                )
                break

        # -- generate -----------------------------------------------------
        yield event(
            "generate",
            "start",
            0.0,
            "loading %s" % cfg.resolved_model(),
            rnd,
        )
        try:
            for b in _unique(backends.values()):
                b.load()
        except RuntimeError as exc:
            backend_error = str(exc)
            raise

        fresh: List[Candidate] = []
        skipped_for_budget = 0
        for n, outcome in enumerate(targets):
            if clock() > cfg.time_budget_s and n > 0:
                skipped_for_budget = len(targets) - n
                yield event(
                    "generate",
                    "progress",
                    n / max(1, len(targets)),
                    "budget spent after paragraph %d of %d; %d left unrewritten"
                    % (n, len(targets), skipped_for_budget),
                    rnd,
                )
                break
            yield event(
                "generate",
                "progress",
                n / max(1, len(targets)),
                "paragraph %d of %d, %d candidates in %s"
                % (
                    n + 1,
                    len(targets),
                    len(specs),
                    "one batch" if len(cfg.styles()) == 1 else "one batch per model",
                ),
                rnd,
            )
            # One batch per style: the instruct and base checkpoints are
            # different backends and `batch_generate` cannot span them.
            para_seconds = 0.0
            para_tps = 0.0
            for style in cfg.styles():
                style_specs = [s for s in specs if s.style == style]
                if not style_specs:
                    continue
                requests = [
                    llm_mod.GenerationRequest(
                        prompt=llm_mod.build_prompt(outcome.original, spec),
                        temperature=spec.temperature,
                        max_tokens=llm_mod.estimate_max_tokens(outcome.original),
                        tag=(outcome.index, spec.index),
                    )
                    for spec in style_specs
                ]
                batch = backends[style].generate(requests)
                generation_seconds += batch.seconds
                generation_tokens += batch.generation_tokens
                used_batching = used_batching or batch.batched
                para_seconds += batch.seconds
                para_tps = batch.tokens_per_second
                stops = llm_mod.STOPS_FOR_STYLE.get(style, ())
                for spec, raw in zip(style_specs, batch.texts):
                    fresh.append(
                        Candidate(
                            paragraph_index=outcome.index,
                            index=spec.index,
                            persona=spec.persona,
                            constraint=spec.constraint,
                            temperature=spec.temperature,
                            round=rnd,
                            raw=llm_mod.clean_completion(raw, stops),
                            style=spec.style,
                        )
                    )
            yield event(
                "generate",
                "progress",
                (n + 1) / max(1, len(targets)),
                "paragraph %d of %d done in %.1fs (%.0f tok/s)"
                % (n + 1, len(targets), para_seconds, para_tps),
                rnd,
            )
        yield event(
            "generate",
            "done",
            1.0,
            "%s in %.1fs, %s"
            % (
                _plural(len(fresh), "candidate"),
                generation_seconds,
                "batched decode" if used_batching else "one at a time",
            ),
            rnd,
        )

        # -- scrub --------------------------------------------------------
        # After the model, never before: the instruct checkpoint reintroduces
        # the vocabulary this pass exists to remove.
        yield event("scrub", "start", 0.0, "applying deterministic transforms", rnd)
        for i, cand in enumerate(fresh):
            cand.scrubbed, cand.scrub_edits = _scrub(cand.raw, cfg.aggressiveness)
            if i % max(1, len(fresh) // 4) == 0 or i == len(fresh) - 1:
                yield event(
                    "scrub",
                    "progress",
                    (i + 1) / max(1, len(fresh)),
                    "candidate %d of %d, paragraph %d of %d"
                    % (
                        cand.index + 1,
                        len(specs),
                        cand.paragraph_index + 1,
                        len(segments),
                    ),
                    rnd,
                )
        n_edits = sum(len(c.scrub_edits) for c in fresh)
        yield event(
            "scrub",
            "done",
            1.0,
            "%s across %s"
            % (_plural(n_edits, "deterministic edit"), _plural(len(fresh), "candidate")),
            rnd,
        )

        # -- score --------------------------------------------------------
        if det is None:
            yield event(
                "score",
                "skip",
                1.0,
                "no detector available; candidates cannot be ranked by score",
                rnd,
            )
        else:
            yield event(
                "score",
                "start",
                0.0,
                "scoring candidates with %s" % _scorer_name(det),
                rnd,
            )
            for i, cand in enumerate(fresh):
                cand.ai_probability = _score(cand.scrubbed, det)
                yield event(
                    "score",
                    "progress",
                    (i + 1) / max(1, len(fresh)),
                    "candidate %d of %d, paragraph %d of %d: %s"
                    % (
                        cand.index + 1,
                        len(specs),
                        cand.paragraph_index + 1,
                        len(segments),
                        "unscored"
                        if cand.ai_probability is None
                        else "p(AI) %.3f" % cand.ai_probability,
                    ),
                    rnd,
                )
            yield event(
                "score",
                "done",
                1.0,
                "scored %d candidates" % len(fresh),
                rnd,
            )

        # -- verify -------------------------------------------------------
        yield event("verify", "start", 0.0, "checking hard gates", rnd)
        by_paragraph: Dict[int, List[Candidate]] = {}
        for i, cand in enumerate(fresh):
            source = outcomes[cand.paragraph_index].original
            cand.gates = _gate_candidate(source, cand.scrubbed, cfg)
            cand.quality = _quality(source, cand.scrubbed) if cand.scrubbed else {}
            by_paragraph.setdefault(cand.paragraph_index, []).append(cand)
            yield event(
                "verify",
                "progress",
                (i + 1) / max(1, len(fresh)),
                "candidate %d of %d, paragraph %d of %d: %s"
                % (
                    cand.index + 1,
                    len(specs),
                    cand.paragraph_index + 1,
                    len(segments),
                    "passed" if cand.passed else "rejected (%s)" % ", ".join(cand.gates),
                ),
                rnd,
            )
        n_passed = sum(1 for c in fresh if c.passed)
        yield event(
            "verify",
            "done",
            1.0,
            "%d of %d candidates passed every gate" % (n_passed, len(fresh)),
            rnd,
        )

        # -- select -------------------------------------------------------
        yield event("select", "start", 0.0, "ranking survivors", rnd)
        for n, (para_index, cands) in enumerate(sorted(by_paragraph.items())):
            outcome = outcomes[para_index]
            outcome.candidates.extend(cands)
            survivors = [c for c in cands if c.passed]
            if not survivors:
                reasons = sorted({g for c in cands for g in c.gates})
                outcome.fallback_reason = (
                    "no candidate passed the gates (%s); kept the original"
                    % ", ".join(reasons)
                )
                yield event(
                    "select",
                    "progress",
                    (n + 1) / max(1, len(by_paragraph)),
                    "paragraph %d of %d: all %d candidates rejected, keeping the "
                    "original" % (para_index + 1, len(segments), len(cands)),
                    rnd,
                )
                continue
            scored = [c for c in survivors if c.ai_probability is not None]
            if scored:
                # Evasion first: the score is the objective. `quality_weight`
                # is the knob that slowly reintroduces the writing bands; at
                # its default of 0.0 this is a pure argmin over the proxy.
                best = min(scored, key=lambda c: _rank_key(c, cfg))
            else:
                # No detector: prefer the candidate whose sentence-length CV is
                # closest to the human band, which is the one measurable target
                # left. Ties go to the earlier (more conservative) candidate.
                best = min(survivors, key=lambda c: (_cv_distance(c), c.index))
            baseline = (
                outcome.ai_probability_after
                if outcome.ai_probability_after is not None
                else outcome.ai_probability_before
            )
            if (
                best.ai_probability is not None
                and baseline is not None
                and best.ai_probability >= baseline
                and rnd > 1
            ):
                # A refinement round may not make a paragraph worse.
                outcome.fallback_reason = (
                    "round %d produced nothing better than round %d" % (rnd, rnd - 1)
                )
            else:
                outcome.chosen = best.scrubbed
                outcome.chosen_index = best.index
                outcome.ai_probability_after = best.ai_probability
                outcome.fallback_reason = None
            yield event(
                "select",
                "progress",
                (n + 1) / max(1, len(by_paragraph)),
                "paragraph %d of %d: candidate %d wins (%s), %d of %d survived"
                % (
                    para_index + 1,
                    len(segments),
                    best.index + 1,
                    "unscored"
                    if best.ai_probability is None
                    else "p(AI) %.3f" % best.ai_probability,
                    len(survivors),
                    len(cands),
                ),
                rnd,
            )
        yield event(
            "select",
            "done",
            1.0,
            "%d of %s rewritten"
            % (
                sum(1 for o in outcomes if o.changed),
                _plural(len(outcomes), "paragraph"),
            ),
            rnd,
        )

    # -- finalize ---------------------------------------------------------
    yield event("finalize", "start", 0.0, "reassembling and re-measuring")
    humanized = "\n\n".join(o.chosen.strip() for o in outcomes if o.chosen.strip())
    after = _measure(humanized, yard)
    p_after = after["ai_probability"]
    all_candidates = [c for o in outcomes for c in o.candidates]
    winning_edits = [
        e
        for o in outcomes
        for c in o.candidates
        if c.index == o.chosen_index and c.paragraph_index == o.index
        for e in c.scrub_edits
    ]
    summary = {
        "engine": "llm",
        "model": cfg.resolved_model(),
        "models": {s: cfg.model_for(s) for s in cfg.styles()},
        "backend": getattr(backend, "name", ""),
        "style": cfg.style,
        "objective": cfg.objective,
        "quality_weight": cfg.quality_weight,
        "gates": {
            "min_content_overlap": cfg.min_content_overlap,
            "max_length_ratio_delta": cfg.max_length_ratio_delta,
            "min_length_ratio": cfg.min_length_ratio,
        },
        # Which model produced each reported number. `yardstick` is the
        # verdict; `candidate_scorer` ranked the candidates. They differ
        # only when the yardstick is GPTZero.
        "yardstick": yard.describe() if isinstance(yard, yardstick_mod.Yardstick) else (
            {"name": _scorer_name(yard), "kind": "caller-supplied"} if yard is not None else None
        ),
        "candidate_scorer": _scorer_name(det) if det is not None else None,
        "winning_styles": {
            s: sum(
                1
                for o in outcomes
                for c in o.candidates
                if c.index == o.chosen_index and c.paragraph_index == o.index and c.style == s
            )
            for s in cfg.styles()
        },
        "n_edits": len(winning_edits),
        "n_paragraphs": len(outcomes),
        "n_candidates_total": len(all_candidates),
        "n_candidates_passed": sum(1 for c in all_candidates if c.passed),
        "n_candidates_rejected": sum(1 for c in all_candidates if not c.passed),
        "gate_rejections": _rejection_counts(all_candidates),
        "paragraphs_rewritten": sum(1 for o in outcomes if o.changed),
        "paragraphs_unchanged": sum(1 for o in outcomes if not o.changed),
        "risk_delta": None
        if (p_before is None or p_after is None)
        else round(p_after - p_before, 6),
        "label_before": before.get("label"),
        "label_after": after.get("label"),
        "verdict_flipped": bool(
            before.get("label") == "ai" and after.get("label") == "human"
        ),
        "seconds": round(clock(), 3),
        "generation_seconds": round(generation_seconds, 3),
        "generation_tokens": generation_tokens,
        # Guarded on a floor rather than on zero: a backend that returns
        # instantly (the test double, a cache hit) would otherwise report a
        # throughput in the millions, which is worse than reporting nothing.
        "tokens_per_second": round(generation_tokens / generation_seconds, 1)
        if generation_seconds > 0.05
        else None,
        "batched": used_batching,
        "quality_flags": _rejection_counts_from_flags(all_candidates),
        "backend_error": backend_error,
    }
    result = LlmHumanizeResult(
        original=original,
        humanized=humanized,
        model=cfg.resolved_model(),
        backend=getattr(backend, "name", ""),
        before=before,
        after=after,
        summary=summary,
        paragraphs=outcomes,
        stages=stage_timings,
        edits=winning_edits,
    )
    detail = "%s in %.1fs" % (
        "verdict flipped ai -> human"
        if summary["verdict_flipped"]
        else "verdict unchanged (%s)" % (after.get("label") or "unscored"),
        summary["seconds"],
    )
    # The finalize timing is appended by hand rather than through `event()` so
    # that it is already in `stage_timings` when the payload is built. A
    # `stages` list that is missing its own last row is the kind of small lie
    # that makes a timing table useless.
    now = clock()
    stage_timings.append(
        {
            "stage": "finalize",
            "status": "done",
            "seconds": round(now - stage_started.pop("finalize", now), 3),
            "detail": detail,
            "round": 1,
        }
    )
    payload = result.as_dict()
    yield ProgressEvent(
        stage="finalize",
        status="done",
        progress=1.0,
        detail=detail,
        elapsed=now,
        round=1,
        result=payload,
        result_object=result,
    )


def _rank_key(candidate: Candidate, cfg: PipelineConfig) -> float:
    """Lower is better. Proxy probability plus a weighted quality penalty.

    The penalty is in the same units as the probability so `quality_weight`
    reads as "how many points of AI probability I would pay for a candidate
    that sits in the human bands". It has two terms, each in [0, 1]: distance
    of the sentence-length CV from the research/10 band, and the share of
    the source's content words the candidate dropped. At weight 0 the key is
    the probability alone, which is the `evade` default.
    """
    p = candidate.ai_probability if candidate.ai_probability is not None else 1.0
    w = float(cfg.quality_weight or 0.0)
    if w <= 0.0:
        return p
    cv_term = min(1.0, _cv_distance(candidate))
    if not math.isfinite(cv_term):
        cv_term = 1.0
    overlap = candidate.quality.get("content_overlap")
    drift_term = 1.0 - float(overlap) if overlap is not None else 0.0
    return p + w * (cv_term + drift_term) / 2.0


def _scorer_name(detector: Any) -> str:
    """A short name for whatever is scoring, for progress details."""
    if detector is None:
        return "nothing"
    if isinstance(detector, yardstick_mod.Yardstick):
        return detector.model if detector.kind == "gptzero" else detector.name
    for attr in ("model_name", "name"):
        value = getattr(detector, attr, None)
        if isinstance(value, str) and value:
            return value
    return type(detector).__name__


def _unique(items: Any) -> List[Any]:
    """Distinct objects by identity, in first-seen order."""
    seen: List[Any] = []
    for item in items:
        if not any(item is s for s in seen):
            seen.append(item)
    return seen


def _cv_distance(candidate: Candidate) -> float:
    """Distance from the human sentence-length CV band. Ranking fallback."""
    cv = candidate.quality.get("sent_len_cv")
    if cv is None:
        return float("inf")
    lo, hi = HUMAN_SENTENCE_CV
    if cv < lo:
        return lo - cv
    if cv > hi:
        return cv - hi
    return 0.0


def _rejection_counts_from_flags(candidates: Sequence[Candidate]) -> Dict[str, int]:
    """How many candidates carried each quality flag.

    Quality flags are advisory, not gates: `possible_semantic_drift` on a
    candidate that passed every gate is exactly the "fluent but wrong" case the
    brief asks to be surfaced rather than silently shipped.
    """
    counts: Dict[str, int] = {}
    for cand in candidates:
        for flag in cand.quality.get("flags", ()):
            counts[flag] = counts.get(flag, 0) + 1
    return dict(sorted(counts.items()))


def _rejection_counts(candidates: Sequence[Candidate]) -> Dict[str, int]:
    """How many candidates each gate rejected. Reported, never hidden."""
    counts: Dict[str, int] = {}
    for cand in candidates:
        for gate in cand.gates:
            counts[gate] = counts.get(gate, 0) + 1
    return dict(sorted(counts.items()))


def humanize_llm(
    text: str,
    config: Optional[PipelineConfig] = None,
    backend: Optional[llm_mod.Backend] = None,
    detector: Any = None,
    on_event: Optional[Callable[[ProgressEvent], None]] = None,
) -> LlmHumanizeResult:
    """Blocking wrapper over `stream()`.

    Drains the event stream and returns the result. `on_event` is called for
    every event as it happens, which is how a caller that wants both the
    progress and the object gets them without re-running the pipeline.
    """
    final: Optional[LlmHumanizeResult] = None
    for ev in stream(text, config=config, backend=backend, detector=detector):
        if on_event is not None:
            on_event(ev)
        if ev.result_object is not None:
            final = ev.result_object
    if final is None:  # pragma: no cover - stream always ends with finalize
        raise RuntimeError("pipeline produced no result")
    return final
